// Code generated by protoc-gen-terraform. DO NOT EDIT.
package v1alpha1

import types "github.com/hashicorp/terraform-plugin-framework/types"

// LoggingConfigModel model
type LoggingConfigModel struct {
	LogLevel          types.Int64 `tfsdk:"log_level"`
	IncludeCaller     types.Bool  `tfsdk:"include_caller"`
	IncludeStackTrace types.Bool  `tfsdk:"include_stack_trace"`
	SendToEventStream types.Bool  `tfsdk:"send_to_event_stream"`
}

// CorsConfigModel model
type CorsConfigModel struct {
	OptionsMode    types.Int64    `tfsdk:"options_mode"`
	AllowedHeaders types.ListType `tfsdk:"allowed_headers"`
	AllowedOrigins types.ListType `tfsdk:"allowed_origins"`
}

// InteractiveClientConfigModel model
type InteractiveClientConfigModel struct {
	InteractionForwardUri    types.String     `tfsdk:"interaction_forward_uri"`
	AllowedRedirectUris      types.ListType   `tfsdk:"allowed_redirect_uris"`
	AccessTokenExpireSeconds types.Int64      `tfsdk:"access_token_expire_seconds"`
	Cors                     types.ObjectType `tfsdk:"cors"`
	Logging                  types.ObjectType `tfsdk:"logging"`
}

// TenantConfigModel model
type TenantConfigModel struct {
	InteractionForwardUri    types.String     `tfsdk:"interaction_forward_uri"`
	AccessTokenExpireSeconds types.Int64      `tfsdk:"access_token_expire_seconds"`
	CookieDomain             types.String     `tfsdk:"cookie_domain"`
	Cors                     types.ObjectType `tfsdk:"cors"`
	Logging                  types.ObjectType `tfsdk:"logging"`
}

// TenantUrlConfigModel model
type TenantUrlConfigModel struct {
	CookieDomain types.String `tfsdk:"cookie_domain"`
}

// AuthorizationConfigModel model
type AuthorizationConfigModel struct {
	IncludeRoles       types.Bool `tfsdk:"include_roles"`
	IncludePermissions types.Bool `tfsdk:"include_permissions"`
}

// ScopesConfigModel model
type ScopesConfigModel struct {
	Openid        types.Bool       `tfsdk:"openid"`
	Authorization types.ObjectType `tfsdk:"authorization"`
}

// AudienceConfigModel model
type AudienceConfigModel struct {
	InteractionForwardUri    types.String     `tfsdk:"interaction_forward_uri"`
	AccessTokenExpireSeconds types.Int64      `tfsdk:"access_token_expire_seconds"`
	Scopes                   types.ObjectType `tfsdk:"scopes"`
	Cors                     types.ObjectType `tfsdk:"cors"`
	Logging                  types.ObjectType `tfsdk:"logging"`
}

// ProviderAuthwiseModel model
type ProviderAuthwiseModel struct {
	Issuer   types.String `tfsdk:"issuer"`
	ClientId types.String `tfsdk:"client_id"`
}

// ProviderUsernamePasswordModel model
type ProviderUsernamePasswordModel struct {
	ForwardUri         types.String   `tfsdk:"forward_uri"`
	PasswordHashType   types.String   `tfsdk:"password_hash_type"`
	PasswordValidators types.ListType `tfsdk:"password_validators"`
}

// ProviderMicrosoftModel model
type ProviderMicrosoftModel struct {
	Scope        types.String `tfsdk:"scope"`
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	PromptStyle  types.String `tfsdk:"prompt_style"`
	Tenant       types.String `tfsdk:"tenant"`
}

// ProviderGoogleModel model
type ProviderGoogleModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	Prompt       types.String `tfsdk:"prompt"`
}

// ProviderGitHubModel model
type ProviderGitHubModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	AllowSignup  types.Bool   `tfsdk:"allow_signup"`
	Prompt       types.String `tfsdk:"prompt"`
	Display      types.String `tfsdk:"display"`
	Scope        types.String `tfsdk:"scope"`
}

// ProviderLinkedInModel model
type ProviderLinkedInModel struct {
	ClientId             types.String `tfsdk:"client_id"`
	ClientSecret         types.String `tfsdk:"client_secret"`
	Scope                types.String `tfsdk:"scope"`
	IncludeGrantedScopes types.String `tfsdk:"include_granted_scopes"`
}

// ProviderFacebookModel model
type ProviderFacebookModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	UserFields   types.String `tfsdk:"user_fields"`
}

// ProviderDropboxModel model
type ProviderDropboxModel struct {
	ClientId             types.String `tfsdk:"client_id"`
	ClientSecret         types.String `tfsdk:"client_secret"`
	Scope                types.String `tfsdk:"scope"`
	IncludeGrantedScopes types.String `tfsdk:"include_granted_scopes"`
}

// ProviderOktaModel model
type ProviderOktaModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	TenantUrl    types.String `tfsdk:"tenant_url"`
}

// ProviderAuth0Model model
type ProviderAuth0Model struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	TenantUrl    types.String `tfsdk:"tenant_url"`
}
