// Code generated by protoc-gen-terraform. DO NOT EDIT.
package v1alpha1

import (
	"context"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// GenSchemaLoggingConfig returns tfsdk.Schema definition for LoggingConfig
func GenSchemaLoggingConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"include_caller": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"include_stack_trace": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"log_level": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"send_to_event_stream": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaCorsConfig returns tfsdk.Schema definition for CorsConfig
func GenSchemaCorsConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"allowed_headers": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
		"allowed_origins": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
		"options_mode": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaInteractiveClientConfig returns tfsdk.Schema definition for InteractiveClientConfig
func GenSchemaInteractiveClientConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"allowed_redirect_uris": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantConfig returns tfsdk.Schema definition for TenantConfig
func GenSchemaTenantConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"cookie_domain": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantUrlConfig returns tfsdk.Schema definition for TenantUrlConfig
func GenSchemaTenantUrlConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{"cookie_domain": schema.StringAttribute{
		Description: "",
		Optional:    true,
	}}}
}

// GenSchemaAuthorizationConfig returns tfsdk.Schema definition for AuthorizationConfig
func GenSchemaAuthorizationConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"include_permissions": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"include_roles": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaScopesConfig returns tfsdk.Schema definition for ScopesConfig
func GenSchemaScopesConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"authorization": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_permissions": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_roles": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"openid": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAudienceConfig returns tfsdk.Schema definition for AudienceConfig
func GenSchemaAudienceConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"scopes": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"authorization": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"include_permissions": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"include_roles": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"openid": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderAuthwise returns tfsdk.Schema definition for ProviderAuthwise
func GenSchemaProviderAuthwise(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"issuer": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderUsernamePassword returns tfsdk.Schema definition for ProviderUsernamePassword
func GenSchemaProviderUsernamePassword(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"forward_uri": schema.StringAttribute{
			Description: "ForwardURI URI to forward to",
			Optional:    true,
		},
		"password_hash_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"password_validators": schema.ListNestedAttribute{
			Description: "",
			NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"config": schema.SingleNestedAttribute{
					Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
					Description: "",
					Optional:    true,
				},
				"name": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"type": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
			}},
			Optional: true,
		},
	}}
}

// GenSchemaProviderMicrosoft returns tfsdk.Schema definition for ProviderMicrosoft
func GenSchemaProviderMicrosoft(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt_style": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderGoogle returns tfsdk.Schema definition for ProviderGoogle
func GenSchemaProviderGoogle(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderGitHub returns tfsdk.Schema definition for ProviderGitHub
func GenSchemaProviderGitHub(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"allow_signup": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"display": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderLinkedIn returns tfsdk.Schema definition for ProviderLinkedIn
func GenSchemaProviderLinkedIn(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"include_granted_scopes": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderFacebook returns tfsdk.Schema definition for ProviderFacebook
func GenSchemaProviderFacebook(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_fields": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderDropbox returns tfsdk.Schema definition for ProviderDropbox
func GenSchemaProviderDropbox(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"include_granted_scopes": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderOkta returns tfsdk.Schema definition for ProviderOkta
func GenSchemaProviderOkta(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderAuth0 returns tfsdk.Schema definition for ProviderAuth0
func GenSchemaProviderAuth0(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
