// Code generated by protoc-gen-terraform. DO NOT EDIT.
package v1alpha1

import types "github.com/hashicorp/terraform-plugin-framework/types"

// AssociationRequestModel model
type AssociationRequestModel struct {
	Set    types.ListType `tfsdk:"set"`
	Remove types.ListType `tfsdk:"remove"`
}

// SearchPredicateDescriptorModel model
type SearchPredicateDescriptorModel struct {
	Name      types.String   `tfsdk:"name"`
	Label     types.String   `tfsdk:"label"`
	Operators types.ListType `tfsdk:"operators"`
}

// SearchPredicateModel model
type SearchPredicateModel struct {
	Name             types.String   `tfsdk:"name"`
	Operator         types.Int64    `tfsdk:"operator"`
	StringValue      types.String   `tfsdk:"string_value"`
	StringArrayValue types.ListType `tfsdk:"string_array_value"`
	NumberValue      types.Float64  `tfsdk:"number_value"`
	NumberArrayValue types.ListType `tfsdk:"number_array_value"`
}

// TenantModel model
type TenantModel struct {
	Id                  types.String     `tfsdk:"id"`
	Name                types.String     `tfsdk:"name"`
	AppearanceProfileId types.String     `tfsdk:"appearance_profile_id"`
	Config              types.ObjectType `tfsdk:"config"`
}

// TenantUrlModel model
type TenantUrlModel struct {
	Id       types.String     `tfsdk:"id"`
	TenantId types.String     `tfsdk:"tenant_id"`
	Config   types.ObjectType `tfsdk:"config"`
}

// UserIdentifierModel model
type UserIdentifierModel struct {
	ProviderId types.String `tfsdk:"provider_id"`
	Identifier types.String `tfsdk:"identifier"`
	Password   types.String `tfsdk:"password"`
}

// UserModel model
type UserModel struct {
	Id                  types.String     `tfsdk:"id"`
	RealmId             types.String     `tfsdk:"realm_id"`
	Name                types.String     `tfsdk:"name"`
	GivenName           types.String     `tfsdk:"given_name"`
	FamilyName          types.String     `tfsdk:"family_name"`
	MiddleName          types.String     `tfsdk:"middle_name"`
	Nickname            types.String     `tfsdk:"nickname"`
	PreferredUsername   types.String     `tfsdk:"preferred_username"`
	Email               types.String     `tfsdk:"email"`
	EmailVerified       types.Bool       `tfsdk:"email_verified"`
	Gender              types.String     `tfsdk:"gender"`
	PhoneNumber         types.String     `tfsdk:"phone_number"`
	PhoneNumberVerified types.Bool       `tfsdk:"phone_number_verified"`
	Profile             types.String     `tfsdk:"profile"`
	Picture             types.String     `tfsdk:"picture"`
	Website             types.String     `tfsdk:"website"`
	Birthdate           types.String     `tfsdk:"birthdate"`
	Zoneinfo            types.String     `tfsdk:"zoneinfo"`
	Locale              types.String     `tfsdk:"locale"`
	Metadata            types.ObjectType `tfsdk:"metadata"`
	ExtraFields         types.ObjectType `tfsdk:"extra_fields"`
	UpdatedAt           types.ObjectType `tfsdk:"updated_at"`
	Identifiers         types.ListType   `tfsdk:"identifiers"`
}

// ProviderModel model
type ProviderModel struct {
	Id           types.String     `tfsdk:"id"`
	RealmId      types.String     `tfsdk:"realm_id"`
	Name         types.String     `tfsdk:"name"`
	ProviderType types.String     `tfsdk:"provider_type"`
	Config       types.ObjectType `tfsdk:"config"`
}

// RealmModel model
type RealmModel struct {
	Id               types.String `tfsdk:"id"`
	TenantId         types.String `tfsdk:"tenant_id"`
	UserDatabaseType types.String `tfsdk:"user_database_type"`
	Name             types.String `tfsdk:"name"`
	Description      types.String `tfsdk:"description"`
}

// AudienceModel model
type AudienceModel struct {
	Id                  types.String     `tfsdk:"id"`
	TenantId            types.String     `tfsdk:"tenant_id"`
	Name                types.String     `tfsdk:"name"`
	AppearanceProfileId types.String     `tfsdk:"appearance_profile_id"`
	Description         types.String     `tfsdk:"description"`
	Config              types.ObjectType `tfsdk:"config"`
}

// ClientModel model
type ClientModel struct {
	Id                  types.String     `tfsdk:"id"`
	AudienceId          types.String     `tfsdk:"audience_id"`
	AppearanceProfileId types.String     `tfsdk:"appearance_profile_id"`
	Name                types.String     `tfsdk:"name"`
	Alias               types.String     `tfsdk:"alias"`
	GrantType           types.String     `tfsdk:"grant_type"`
	LoginUrl            types.String     `tfsdk:"login_url"`
	LogoId              types.String     `tfsdk:"logo_id"`
	Config              types.ObjectType `tfsdk:"config"`
	Metadata            types.ObjectType `tfsdk:"metadata"`
}

// RoleModel model
type RoleModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Name       types.String `tfsdk:"name"`
	Auto       types.Bool   `tfsdk:"auto"`
}

// PermissionModel model
type PermissionModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Name       types.String `tfsdk:"name"`
}

// ScopeModel model
type ScopeModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Kind       types.String `tfsdk:"kind"`
	Auto       types.Bool   `tfsdk:"auto"`
}

// EventModel model
type EventModel struct {
	Id            types.String     `tfsdk:"id"`
	TenantId      types.String     `tfsdk:"tenant_id"`
	RequestId     types.String     `tfsdk:"request_id"`
	ClientId      types.String     `tfsdk:"client_id"`
	RealmId       types.String     `tfsdk:"realm_id"`
	UserId        types.String     `tfsdk:"user_id"`
	SessionId     types.String     `tfsdk:"session_id"`
	InteractionId types.String     `tfsdk:"interaction_id"`
	EventType     types.String     `tfsdk:"event_type"`
	EventMessage  types.String     `tfsdk:"event_message"`
	StartState    types.String     `tfsdk:"start_state"`
	EndState      types.String     `tfsdk:"end_state"`
	StartTime     types.ObjectType `tfsdk:"start_time"`
	EndTime       types.ObjectType `tfsdk:"end_time"`
	Attributes    types.ObjectType `tfsdk:"attributes"`
	CreatedAt     types.ObjectType `tfsdk:"created_at"`
}

// AppearanceProfileModel model
type AppearanceProfileModel struct {
	Id                   types.String     `tfsdk:"id"`
	Name                 types.String     `tfsdk:"name"`
	TenantId             types.String     `tfsdk:"tenant_id"`
	ThemeId              types.String     `tfsdk:"theme_id"`
	StylesheetAttributes types.ObjectType `tfsdk:"stylesheet_attributes"`
	Content              types.ObjectType `tfsdk:"content"`
}

// ThemeModel model
type ThemeModel struct {
	Id                   types.String     `tfsdk:"id"`
	TenantId             types.String     `tfsdk:"tenant_id"`
	Name                 types.String     `tfsdk:"name"`
	Stylesheet           types.String     `tfsdk:"stylesheet"`
	StylesheetAttributes types.ObjectType `tfsdk:"stylesheet_attributes"`
	Content              types.ObjectType `tfsdk:"content"`
}

// SecuredUserModel model
type SecuredUserModel struct {
	Audience types.String     `tfsdk:"audience"`
	Jti      types.String     `tfsdk:"jti"`
	User     types.ObjectType `tfsdk:"user"`
}

// SecretModel model
type SecretModel struct {
	Id       types.String `tfsdk:"id"`
	TenantId types.String `tfsdk:"tenant_id"`
	Name     types.String `tfsdk:"name"`
	Encoding types.Int64  `tfsdk:"encoding"`
	Value    types.String `tfsdk:"value"`
}

// AssetModel model
type AssetModel struct {
	Id       types.String `tfsdk:"id"`
	TenantId types.String `tfsdk:"tenant_id"`
	Name     types.String `tfsdk:"name"`
	MimeType types.String `tfsdk:"mime_type"`
}
