// Code generated by protoc-gen-terraform. DO NOT EDIT.
package v1alpha1

import (
	"context"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// GenSchemaAssociationRequest returns tfsdk.Schema definition for AssociationRequest
func GenSchemaAssociationRequest(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"remove": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
		"set": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
	}}
}

// GenSchemaSearchPredicateDescriptor returns tfsdk.Schema definition for SearchPredicateDescriptor
func GenSchemaSearchPredicateDescriptor(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"label": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"operators": schema.ListAttribute{
			Description: "",
			ElementType: types.Int64Type,
			Optional:    true,
		},
	}}
}

// GenSchemaSearchPredicate returns tfsdk.Schema definition for SearchPredicate
func GenSchemaSearchPredicate(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"number_array_value": schema.ListAttribute{
			Description: "",
			ElementType: types.Float64Type,
			Optional:    true,
		},
		"number_value": schema.Float64Attribute{
			Description: "",
			Optional:    true,
		},
		"operator": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"string_array_value": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
		"string_value": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenant returns tfsdk.Schema definition for Tenant
func GenSchemaTenant(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"access_token_expire_seconds": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"cookie_domain": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"cors": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"allowed_headers": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"allowed_origins": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"options_mode": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"interaction_forward_uri": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"logging": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"include_caller": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"include_stack_trace": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"log_level": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
						"send_to_event_stream": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantUrl returns tfsdk.Schema definition for TenantUrl
func GenSchemaTenantUrl(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"cookie_domain": schema.StringAttribute{
				Description: "",
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaUserIdentifier returns tfsdk.Schema definition for UserIdentifier
func GenSchemaUserIdentifier(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"identifier": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"password": schema.StringAttribute{
			Description: "Only used for creating",
			Optional:    true,
		},
		"provider_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaUser returns tfsdk.Schema definition for User
func GenSchemaUser(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"birthdate": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"email": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"email_verified": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"extra_fields": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"family_name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"gender": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"given_name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"identifiers": schema.ListNestedAttribute{
			Description: "",
			NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"identifier": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"password": schema.StringAttribute{
					Description: "Only used for creating",
					Optional:    true,
				},
				"provider_id": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
			}},
			Optional: true,
		},
		"locale": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"metadata": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"middle_name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"nickname": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"phone_number": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"phone_number_verified": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"picture": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"preferred_username": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"profile": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"realm_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"updated_at": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"nanos": schema.Int64Attribute{
					Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
					Optional:    true,
				},
				"seconds": schema.Int64Attribute{
					Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"website": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"zoneinfo": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProvider returns tfsdk.Schema definition for Provider
func GenSchemaProvider(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"type_url": schema.StringAttribute{
					Description: "A URL/resource name that uniquely identifies the type of the serialized protocol buffer message. This string must contain at least one \"/\" character. The last segment of the URL's path must represent the fully qualified name of the type (as in `path/google.protobuf.Duration`). The name should be in a canonical form (e.g., leading \".\" is not accepted). In practice, teams usually precompile into the binary all types that they expect it to use in the context of Any. However, for URLs which use the scheme `http`, `https`, or no scheme, one can optionally set up a type server that maps type URLs to message definitions as follows: * If no scheme is provided, `https` is assumed. * An HTTP GET on the URL must yield a [google.protobuf.Type][]   value in binary format, or produce an error. * Applications are allowed to cache lookup results based on the   URL, or have them precompiled into a binary to avoid any   lookup. Therefore, binary compatibility needs to be preserved   on changes to types. (Use versioned type names to manage   breaking changes.) Note: this functionality is not currently available in the official protobuf release, and it is not used for type URLs beginning with type.googleapis.com. Schemes other than `http`, `https` (or the empty scheme) might be used with implementation specific semantics.",
					Optional:    true,
				},
				"value": schema.StringAttribute{
					Description: "Must be a valid serialized protocol buffer of the above specified type.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"provider_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"realm_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaRealm returns tfsdk.Schema definition for Realm
func GenSchemaRealm(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"description": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:      true,
			Optional:      false,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			Required:      false,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_database_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAudience returns tfsdk.Schema definition for Audience
func GenSchemaAudience(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"access_token_expire_seconds": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"cors": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"allowed_headers": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"allowed_origins": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"options_mode": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"interaction_forward_uri": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"logging": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"include_caller": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"include_stack_trace": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"log_level": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
						"send_to_event_stream": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"scopes": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"authorization": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"include_permissions": schema.BoolAttribute{
									Description: "",
									Optional:    true,
								},
								"include_roles": schema.BoolAttribute{
									Description: "",
									Optional:    true,
								},
							},
							Description: "",
							Optional:    true,
						},
						"openid": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"description": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaClient returns tfsdk.Schema definition for Client
func GenSchemaClient(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"alias": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"type_url": schema.StringAttribute{
					Description: "A URL/resource name that uniquely identifies the type of the serialized protocol buffer message. This string must contain at least one \"/\" character. The last segment of the URL's path must represent the fully qualified name of the type (as in `path/google.protobuf.Duration`). The name should be in a canonical form (e.g., leading \".\" is not accepted). In practice, teams usually precompile into the binary all types that they expect it to use in the context of Any. However, for URLs which use the scheme `http`, `https`, or no scheme, one can optionally set up a type server that maps type URLs to message definitions as follows: * If no scheme is provided, `https` is assumed. * An HTTP GET on the URL must yield a [google.protobuf.Type][]   value in binary format, or produce an error. * Applications are allowed to cache lookup results based on the   URL, or have them precompiled into a binary to avoid any   lookup. Therefore, binary compatibility needs to be preserved   on changes to types. (Use versioned type names to manage   breaking changes.) Note: this functionality is not currently available in the official protobuf release, and it is not used for type URLs beginning with type.googleapis.com. Schemes other than `http`, `https` (or the empty scheme) might be used with implementation specific semantics.",
					Optional:    true,
				},
				"value": schema.StringAttribute{
					Description: "Must be a valid serialized protocol buffer of the above specified type.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"grant_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"login_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logo_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"metadata": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaRole returns tfsdk.Schema definition for Role
func GenSchemaRole(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaPermission returns tfsdk.Schema definition for Permission
func GenSchemaPermission(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaScope returns tfsdk.Schema definition for Scope
func GenSchemaScope(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"kind": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaEvent returns tfsdk.Schema definition for Event
func GenSchemaEvent(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"attributes": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"created_at": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"nanos": schema.Int64Attribute{
					Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
					Optional:    true,
				},
				"seconds": schema.Int64Attribute{
					Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"end_state": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"end_time": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"nanos": schema.Int64Attribute{
					Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
					Optional:    true,
				},
				"seconds": schema.Int64Attribute{
					Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"event_message": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"event_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"interaction_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"realm_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"request_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"session_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"start_state": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"start_time": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"nanos": schema.Int64Attribute{
					Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
					Optional:    true,
				},
				"seconds": schema.Int64Attribute{
					Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAppearanceProfile returns tfsdk.Schema definition for AppearanceProfile
func GenSchemaAppearanceProfile(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"theme_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTheme returns tfsdk.Schema definition for Theme
func GenSchemaTheme(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaSecuredUser returns tfsdk.Schema definition for SecuredUser
func GenSchemaSecuredUser(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"jti": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"birthdate": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"email": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"email_verified": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"extra_fields": schema.SingleNestedAttribute{
					Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
					Description: "",
					Optional:    true,
				},
				"family_name": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"gender": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"given_name": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"id": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"identifiers": schema.ListNestedAttribute{
					Description: "",
					NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
						"identifier": schema.StringAttribute{
							Description: "",
							Optional:    true,
						},
						"password": schema.StringAttribute{
							Description: "Only used for creating",
							Optional:    true,
						},
						"provider_id": schema.StringAttribute{
							Description: "",
							Optional:    true,
						},
					}},
					Optional: true,
				},
				"locale": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"metadata": schema.SingleNestedAttribute{
					Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
					Description: "",
					Optional:    true,
				},
				"middle_name": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"name": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"nickname": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"phone_number": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"phone_number_verified": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"picture": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"preferred_username": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"profile": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"realm_id": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"updated_at": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"nanos": schema.Int64Attribute{
							Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
							Optional:    true,
						},
						"seconds": schema.Int64Attribute{
							Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"website": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"zoneinfo": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaSecret returns tfsdk.Schema definition for Secret
func GenSchemaSecret(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"encoding": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"value": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAsset returns tfsdk.Schema definition for Asset
func GenSchemaAsset(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"mime_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
