// Code generated by protoc-gen-terraform. DO NOT EDIT.
package v1alpha1

import types "github.com/hashicorp/terraform-plugin-framework/types"

// PasswordValidatorConfigModel model
type PasswordValidatorConfigModel struct {
	Name   types.String     `tfsdk:"name"`
	Type   types.String     `tfsdk:"type"`
	Config types.ObjectType `tfsdk:"config"`
}
