// Code generated by protoc-gen-terraform. DO NOT EDIT.
package v1alpha1

import (
	"context"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

// GenSchemaPasswordValidatorConfig returns tfsdk.Schema definition for PasswordValidatorConfig
func GenSchemaPasswordValidatorConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
