// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type appearanceProfileResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewAppearanceProfile() resource.Resource {
	return &appearanceProfileResource{}
}

type appearanceProfileModel struct {
	Id                   types.String `tfsdk:"id"`
	Name                 types.String `tfsdk:"name"`
	TenantId             types.String `tfsdk:"tenant_id"`
	ThemeId              types.String `tfsdk:"theme_id"`
	StylesheetAttributes types.Object `tfsdk:"stylesheet_attributes"`
	Content              types.Object `tfsdk:"content"`
}

func (r *appearanceProfileResource) toProto(m *appearanceProfileModel) *v1alpha11.AppearanceProfile {
	return &v1alpha11.AppearanceProfile{
		Content:              nil,
		Id:                   m.Id.ValueString(),
		Name:                 m.Name.ValueString(),
		StylesheetAttributes: nil,
		TenantId:             m.TenantId.ValueString(),
		ThemeId:              m.ThemeId.ValueString(),
	}
}

func (r *appearanceProfileResource) toModel(p *v1alpha11.AppearanceProfile, m *appearanceProfileModel) {
	m.Id = types.StringValue(p.Id)
	m.Name = types.StringValue(p.Name)
	m.TenantId = types.StringValue(p.TenantId)
	m.ThemeId = types.StringValue(p.ThemeId)
}

func (r *appearanceProfileResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *appearanceProfileResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_appearance_profile"
}

func (r *appearanceProfileResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaAppearanceProfile(ctx)
}

func (r *appearanceProfileResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data appearanceProfileModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	cr := &v1alpha1.CreateAppearanceProfileRequest{AppearanceProfile: r.toProto(&data)}
	resp, err := r.client.CreateAppearanceProfile(ctx, cr)
	if err != nil {
		response.Diagnostics.AddError("Error Creating AppearanceProfile", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "appearanceprofile create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *appearanceProfileResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (r *appearanceProfileResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (r *appearanceProfileResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
