// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
	util "terraform-provider-authwise/internal/util"
)

type appearanceProfileResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewAppearanceProfile() resource.Resource {
	return &appearanceProfileResource{}
}

type appearanceProfileModel struct {
	Id                   types.String `tfsdk:"id"`
	Name                 types.String `tfsdk:"name"`
	TenantId             types.String `tfsdk:"tenant_id"`
	ThemeId              types.String `tfsdk:"theme_id"`
	StylesheetAttributes types.Object `tfsdk:"stylesheet_attributes"`
	Content              types.Object `tfsdk:"content"`
}

func (r *appearanceProfileResource) toName(data appearanceProfileModel) string {
	return fmt.Sprintf("appearance_profiles/%s", data.Id.ValueString())
}
func (r *appearanceProfileResource) toProto(m *appearanceProfileModel) (*v1alpha11.AppearanceProfile, error) {
	converted_stylesheetattributes, err := util.ObjectToProtoStruct(m.StylesheetAttributes)
	if err != nil {
		return nil, err
	}
	converted_content, err := util.ObjectToProtoStruct(m.Content)
	if err != nil {
		return nil, err
	}
	return &v1alpha11.AppearanceProfile{
		Content:              converted_content,
		Id:                   m.Id.ValueString(),
		Name:                 m.Name.ValueString(),
		StylesheetAttributes: converted_stylesheetattributes,
		TenantId:             m.TenantId.ValueString(),
		ThemeId:              m.ThemeId.ValueString(),
	}, nil
}

func (r *appearanceProfileResource) toModel(p *v1alpha11.AppearanceProfile, m *appearanceProfileModel) error {
	m.Id = types.StringValue(p.Id)
	m.Name = types.StringValue(p.Name)
	m.TenantId = types.StringValue(p.TenantId)
	m.ThemeId = types.StringValue(p.ThemeId)
	converted_stylesheetattributes, err := util.ProtoStructToObject(p.StylesheetAttributes)
	if err != nil {
		return err
	}
	m.StylesheetAttributes = *converted_stylesheetattributes
	converted_content, err := util.ProtoStructToObject(p.Content)
	if err != nil {
		return err
	}
	m.Content = *converted_content
	return nil
}

func (r *appearanceProfileResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *appearanceProfileResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_appearance_profile"
}

func (r *appearanceProfileResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaAppearanceProfile(ctx)
}

func (r *appearanceProfileResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data appearanceProfileModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting AppearanceProfile to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreateAppearanceProfileRequest{AppearanceProfile: val}
	resp, err := r.client.CreateAppearanceProfile(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating AppearanceProfile", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting AppearanceProfile to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "appearanceprofile create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *appearanceProfileResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data appearanceProfileModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetAppearanceProfileRequest{Name: r.toName(data)}
	resp, err := r.client.GetAppearanceProfile(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading AppearanceProfile", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting AppearanceProfile to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "appearanceprofile read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *appearanceProfileResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data appearanceProfileModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting AppearanceProfile to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdateAppearanceProfileRequest{
		AppearanceProfile: val,
		Name:              r.toName(data),
	}
	resp, err := r.client.UpdateAppearanceProfile(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating AppearanceProfile", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting AppearanceProfile to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "appearanceprofile update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *appearanceProfileResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data appearanceProfileModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteAppearanceProfileRequest{Name: r.toName(data)}
	_, err := r.client.DeleteAppearanceProfile(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting AppearanceProfile", err.Error())
		return
	}
	return
}
