// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type assetDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewAssetDataSource() datasource.DataSource {
	return &assetDataSource{}
}

func (r *assetDataSource) toName(data assetDataSourceModel) string {
	return fmt.Sprintf("assets/%s", data.Id.ValueString())
}
func (r *assetDataSource) toModel(p *v1alpha11.Asset, m *assetDataSourceModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.Name = types.StringValue(p.Name)
	m.MimeType = types.StringValue(p.MimeType)
}

type assetDataSourceModel struct {
	Id       types.String `tfsdk:"id"`
	TenantId types.String `tfsdk:"tenant_id"`
	Name     types.String `tfsdk:"name"`
	MimeType types.String `tfsdk:"mime_type"`
}

func (r *assetDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *assetDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_asset"
}

func (r *assetDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{Attributes: map[string]schema.Attribute{"id": schema.StringAttribute{
		Description: "",
		Required:    true,
	}}}
}

func (r *assetDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data assetDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetAssetRequest{Name: r.toName(data)}
	resp, err := r.client.GetAsset(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Asset", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "asset read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
