// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type assetResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewAsset() resource.Resource {
	return &assetResource{}
}

type assetModel struct {
	Id       types.String `tfsdk:"id"`
	TenantId types.String `tfsdk:"tenant_id"`
	Name     types.String `tfsdk:"name"`
	MimeType types.String `tfsdk:"mime_type"`
}

func (r *assetResource) toProto(m *assetModel) *v1alpha11.Asset {
	return &v1alpha11.Asset{
		Id:       m.Id.ValueString(),
		MimeType: m.MimeType.ValueString(),
		Name:     m.Name.ValueString(),
		TenantId: m.TenantId.ValueString(),
	}
}

func (r *assetResource) toModel(p *v1alpha11.Asset, m *assetModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.Name = types.StringValue(p.Name)
	m.MimeType = types.StringValue(p.MimeType)
}

func (r *assetResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *assetResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_asset"
}

func (r *assetResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaAsset(ctx)
}

func (r *assetResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data assetModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	cr := &v1alpha1.CreateAssetRequest{Asset: r.toProto(&data)}
	resp, err := r.client.CreateAsset(ctx, cr)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Asset", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "asset create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *assetResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (r *assetResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (r *assetResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
