// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
	util "terraform-provider-authwise/internal/util"
)

type audienceResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewAudience() resource.Resource {
	return &audienceResource{}
}

type audienceModel struct {
	Id                  types.String `tfsdk:"id"`
	TenantId            types.String `tfsdk:"tenant_id"`
	Name                types.String `tfsdk:"name"`
	AppearanceProfileId types.String `tfsdk:"appearance_profile_id"`
	Description         types.String `tfsdk:"description"`
	Config              types.Object `tfsdk:"config"`
}

func (r *audienceResource) toName(data audienceModel) string {
	return fmt.Sprintf("audiences/%s", data.Id.ValueString())
}
func (r *audienceResource) toProto(m *audienceModel) (*v1alpha11.Audience, error) {
	converted_config, err := util.ObjectToProtoConcrete[v1alpha11.AudienceConfig](m.Config)
	if err != nil {
		return nil, err
	}
	return &v1alpha11.Audience{
		AppearanceProfileId: m.AppearanceProfileId.ValueString(),
		Config:              converted_config,
		Description:         m.Description.ValueString(),
		Id:                  m.Id.ValueString(),
		Name:                m.Name.ValueString(),
		TenantId:            m.TenantId.ValueString(),
	}, nil
}

func (r *audienceResource) toModel(p *v1alpha11.Audience, m *audienceModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.Name = types.StringValue(p.Name)
	m.AppearanceProfileId = types.StringValue(p.AppearanceProfileId)
	m.Description = types.StringValue(p.Description)
}

func (r *audienceResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *audienceResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_audience"
}

func (r *audienceResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaAudience(ctx)
}

func (r *audienceResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data audienceModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Audience to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreateAudienceRequest{Audience: val}
	resp, err := r.client.CreateAudience(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Audience", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "audience create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *audienceResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data audienceModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetAudienceRequest{Name: r.toName(data)}
	resp, err := r.client.GetAudience(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Audience", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "audience read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *audienceResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data audienceModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Audience to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdateAudienceRequest{
		Audience: val,
		Name:     r.toName(data),
	}
	resp, err := r.client.UpdateAudience(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Audience", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "audience update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *audienceResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data audienceModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteAudienceRequest{Name: r.toName(data)}
	_, err := r.client.DeleteAudience(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Audience", err.Error())
		return
	}
	return
}
