// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type audienceDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewAudienceDataSource() datasource.DataSource {
	return &audienceDataSource{}
}

func (r *audienceDataSource) toName(data audienceDataSourceModel) string {
	return fmt.Sprintf("audiences/%s", data.Id.ValueString())
}
func (r *audienceDataSource) toModel(p *v1alpha11.Audience, m *audienceDataSourceModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.Name = types.StringValue(p.Name)
	m.AppearanceProfileId = types.StringValue(p.AppearanceProfileId)
	m.Description = types.StringValue(p.Description)
}

type audienceDataSourceModel struct {
	Id                  types.String `tfsdk:"id"`
	TenantId            types.String `tfsdk:"tenant_id"`
	Name                types.String `tfsdk:"name"`
	AppearanceProfileId types.String `tfsdk:"appearance_profile_id"`
	Description         types.String `tfsdk:"description"`
	Config              types.Object `tfsdk:"config"`
}

func (r *audienceDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *audienceDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_audience"
}

func (r *audienceDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{Attributes: map[string]schema.Attribute{"id": schema.StringAttribute{
		Description: "",
		Required:    true,
	}}}
}

func (r *audienceDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data audienceDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetAudienceRequest{Name: r.toName(data)}
	resp, err := r.client.GetAudience(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Audience", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "audience read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
