// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type clientDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewClientDataSource() datasource.DataSource {
	return &clientDataSource{}
}

func (r *clientDataSource) toName(data clientDataSourceModel) string {
	return fmt.Sprintf("clients/%s", data.Id.ValueString())
}
func (r *clientDataSource) toModel(p *v1alpha11.Client, m *clientDataSourceModel) {
	m.Id = types.StringValue(p.Id)
	m.AudienceId = types.StringValue(p.AudienceId)
	m.AppearanceProfileId = types.StringValue(p.AppearanceProfileId)
	m.Name = types.StringValue(p.Name)
	m.Alias = types.StringValue(p.Alias)
	m.GrantType = types.StringValue(p.GrantType)
	m.LoginUrl = types.StringValue(p.LoginUrl)
	m.LogoId = types.StringValue(p.LogoId)
}

type clientDataSourceModel struct {
	Id                  types.String `tfsdk:"id"`
	AudienceId          types.String `tfsdk:"audience_id"`
	AppearanceProfileId types.String `tfsdk:"appearance_profile_id"`
	Name                types.String `tfsdk:"name"`
	Alias               types.String `tfsdk:"alias"`
	GrantType           types.String `tfsdk:"grant_type"`
	LoginUrl            types.String `tfsdk:"login_url"`
	LogoId              types.String `tfsdk:"logo_id"`
	Config              types.Object `tfsdk:"config"`
	Metadata            types.Object `tfsdk:"metadata"`
}

func (r *clientDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *clientDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_client"
}

func (r *clientDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{Attributes: map[string]schema.Attribute{"id": schema.StringAttribute{
		Description: "",
		Required:    true,
	}}}
}

func (r *clientDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data clientDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetClientRequest{Name: r.toName(data)}
	resp, err := r.client.GetClient(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Client", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "client read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
