// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type clientResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewClient() resource.Resource {
	return &clientResource{}
}

type clientModel struct {
	Id                  types.String `tfsdk:"id"`
	AudienceId          types.String `tfsdk:"audience_id"`
	AppearanceProfileId types.String `tfsdk:"appearance_profile_id"`
	Name                types.String `tfsdk:"name"`
	Alias               types.String `tfsdk:"alias"`
	GrantType           types.String `tfsdk:"grant_type"`
	LoginUrl            types.String `tfsdk:"login_url"`
	LogoId              types.String `tfsdk:"logo_id"`
	Config              types.Object `tfsdk:"config"`
	Metadata            types.Object `tfsdk:"metadata"`
}

func (r *clientResource) toProto(m *clientModel) *v1alpha11.Client {
	return &v1alpha11.Client{
		Alias:               m.Alias.ValueString(),
		AppearanceProfileId: m.AppearanceProfileId.ValueString(),
		AudienceId:          m.AudienceId.ValueString(),
		Config:              nil,
		GrantType:           m.GrantType.ValueString(),
		Id:                  m.Id.ValueString(),
		LoginUrl:            m.LoginUrl.ValueString(),
		LogoId:              m.LogoId.ValueString(),
		Metadata:            nil,
		Name:                m.Name.ValueString(),
	}
}

func (r *clientResource) toModel(p *v1alpha11.Client, m *clientModel) {
	m.Id = types.StringValue(p.Id)
	m.AudienceId = types.StringValue(p.AudienceId)
	m.AppearanceProfileId = types.StringValue(p.AppearanceProfileId)
	m.Name = types.StringValue(p.Name)
	m.Alias = types.StringValue(p.Alias)
	m.GrantType = types.StringValue(p.GrantType)
	m.LoginUrl = types.StringValue(p.LoginUrl)
	m.LogoId = types.StringValue(p.LogoId)
}

func (r *clientResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *clientResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_client"
}

func (r *clientResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaClient(ctx)
}

func (r *clientResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data clientModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	cr := &v1alpha1.CreateClientRequest{Client: r.toProto(&data)}
	resp, err := r.client.CreateClient(ctx, cr)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Client", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "client create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *clientResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (r *clientResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (r *clientResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
