// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type providerGitHubDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewProviderGitHub() datasource.DataSource {
	return &providerGitHubDataSource{}
}

type providerGitHubDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	AllowSignup  types.Bool   `tfsdk:"allow_signup"`
	Prompt       types.String `tfsdk:"prompt"`
	Display      types.String `tfsdk:"display"`
	Scope        types.String `tfsdk:"scope"`
}

func (r *providerGitHubDataSource) toProto(m *providerGitHubDataSourceModel) *v1alpha11.ProviderGitHub {
	return &v1alpha11.ProviderGitHub{
		AllowSignup:  m.AllowSignup.ValueBool(),
		ClientId:     m.ClientId.ValueString(),
		ClientSecret: m.ClientSecret.ValueString(),
		Display:      m.Display.ValueString(),
		Prompt:       m.Prompt.ValueString(),
		Scope:        m.Scope.ValueString(),
	}
}

func (r *providerGitHubDataSource) toModel(p *v1alpha11.ProviderGitHub, m *providerGitHubDataSourceModel) {
	m.ClientId = types.StringValue(p.ClientId)
	m.ClientSecret = types.StringValue(p.ClientSecret)
	m.AllowSignup = types.BoolValue(p.AllowSignup)
	m.Prompt = types.StringValue(p.Prompt)
	m.Display = types.StringValue(p.Display)
	m.Scope = types.StringValue(p.Scope)
}

func (r *providerGitHubDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *providerGitHubDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_git_hub"
}

func (r *providerGitHubDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerGitHubDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderGitHubRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderGitHub(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderGitHub", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providergithub read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
