// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type providerFacebookDataSource struct{}

func NewProviderFacebook() datasource.DataSource {
	return &providerFacebookDataSource{}
}

type providerFacebookDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	UserFields   types.String `tfsdk:"user_fields"`
	Type         types.String `tfsdk:"type"`
}

func (r *providerFacebookDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_facebook"
}

func (r *providerFacebookDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderFacebookDataSource(ctx)
}

func (r *providerFacebookDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerFacebookDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderFacebookRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderFacebook(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderFacebook", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerfacebook read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
