// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type providerGoogleDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewProviderGoogle() datasource.DataSource {
	return &providerGoogleDataSource{}
}

type providerGoogleDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	Prompt       types.String `tfsdk:"prompt"`
}

func (r *providerGoogleDataSource) toProto(m *providerGoogleDataSourceModel) *v1alpha11.ProviderGoogle {
	return &v1alpha11.ProviderGoogle{
		ClientId:     m.ClientId.ValueString(),
		ClientSecret: m.ClientSecret.ValueString(),
		Prompt:       m.Prompt.ValueString(),
		Scope:        m.Scope.ValueString(),
	}
}

func (r *providerGoogleDataSource) toModel(p *v1alpha11.ProviderGoogle, m *providerGoogleDataSourceModel) {
	m.ClientId = types.StringValue(p.ClientId)
	m.ClientSecret = types.StringValue(p.ClientSecret)
	m.Scope = types.StringValue(p.Scope)
	m.Prompt = types.StringValue(p.Prompt)
}

func (r *providerGoogleDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *providerGoogleDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_google"
}

func (r *providerGoogleDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerGoogleDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderGoogleRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderGoogle(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderGoogle", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providergoogle read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
