// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type tenantUrlConfigDataSource struct{}

func NewTenantUrlConfig() datasource.DataSource {
	return &tenantUrlConfigDataSource{}
}

type tenantUrlConfigDataSourceModel struct {
	CookieDomain types.String `tfsdk:"cookie_domain"`
	Json         types.String `tfsdk:"json"`
}

func (r *tenantUrlConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_tenant_url_config"
}

func (r *tenantUrlConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaTenantUrlConfigDataSource(ctx)
}

func (r *tenantUrlConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data tenantUrlConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetTenantUrlConfigRequest{Name: r.toName(data)}
	resp, err := r.client.GetTenantUrlConfig(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading TenantUrlConfig", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "tenanturlconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
