// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerMicrosoftDataSource struct{}

func NewProviderMicrosoft() datasource.DataSource {
	return &providerMicrosoftDataSource{}
}

type providerMicrosoftDataSourceModel struct {
	Scope        types.String         `tfsdk:"scope"`
	ClientId     types.String         `tfsdk:"client_id"`
	ClientSecret types.String         `tfsdk:"client_secret"`
	PromptStyle  types.String         `tfsdk:"prompt_style"`
	Tenant       types.String         `tfsdk:"tenant"`
	Result       jsontypes.Normalized `tfsdk:"result"`
}

func (r *providerMicrosoftDataSource) computeResult(ctx context.Context, m *providerMicrosoftDataSourceModel) (*jsontypes.Normalized, error) {

	converted := map[string]any{
		"@type":         "type.googleapis.com/authwise.types.core.v1alpha1.ProviderMicrosoft",
		"client_id":     m.ClientId.ValueString(),
		"client_secret": m.ClientSecret.ValueString(),
		"prompt_style":  m.PromptStyle.ValueString(),
		"scope":         m.Scope.ValueString(),
		"tenant":        m.Tenant.ValueString(),
	}
	j, err := json.Marshal(converted)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *providerMicrosoftDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_microsoft"
}

func (r *providerMicrosoftDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderMicrosoftDataSource(ctx)
}

func (r *providerMicrosoftDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerMicrosoftDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "providermicrosoft read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
