// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerDropboxDataSource struct{}

func NewProviderDropbox() datasource.DataSource {
	return &providerDropboxDataSource{}
}

type providerDropboxDataSourceModel struct {
	ClientId             types.String `tfsdk:"client_id"`
	ClientSecret         types.String `tfsdk:"client_secret"`
	Scope                types.String `tfsdk:"scope"`
	IncludeGrantedScopes types.String `tfsdk:"include_granted_scopes"`
	Result               types.Object `tfsdk:"Result"`
}

func (r *providerDropboxDataSource) computeResult(ctx context.Context, m *providerDropboxDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":                types.StringType,
		"ClientId":             m.ClientId.Type(ctx),
		"ClientSecret":         m.ClientSecret.Type(ctx),
		"IncludeGrantedScopes": m.IncludeGrantedScopes.Type(ctx),
		"Scope":                m.Scope.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":                types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderDropbox"),
		"ClientId":             m.ClientId,
		"ClientSecret":         m.ClientSecret,
		"IncludeGrantedScopes": m.IncludeGrantedScopes,
		"Scope":                m.Scope,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerDropboxDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_dropbox"
}

func (r *providerDropboxDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderDropboxDataSource(ctx)
}

func (r *providerDropboxDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerDropboxDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providerdropbox read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
