// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type interactiveClientConfigDataSource struct{}

func NewInteractiveClientConfig() datasource.DataSource {
	return &interactiveClientConfigDataSource{}
}

type interactiveClientConfigDataSourceModel struct {
	InteractionForwardUri    types.String `tfsdk:"interaction_forward_uri"`
	AllowedRedirectUris      types.List   `tfsdk:"allowed_redirect_uris"`
	AccessTokenExpireSeconds types.Int64  `tfsdk:"access_token_expire_seconds"`
	Cors                     types.Object `tfsdk:"cors"`
	Logging                  types.Object `tfsdk:"logging"`
	Result                   types.Object `tfsdk:"result"`
}

func (r *interactiveClientConfigDataSource) computeResult(ctx context.Context, m *interactiveClientConfigDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":                       types.StringType,
		"access_token_expire_seconds": m.AccessTokenExpireSeconds.Type(ctx),
		"allowed_redirect_uris":       m.AllowedRedirectUris.Type(ctx),
		"cors":                        m.Cors.Type(ctx),
		"interaction_forward_uri":     m.InteractionForwardUri.Type(ctx),
		"logging":                     m.Logging.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":                       types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.InteractiveClientConfig"),
		"access_token_expire_seconds": m.AccessTokenExpireSeconds,
		"allowed_redirect_uris":       m.AllowedRedirectUris,
		"cors":                        m.Cors,
		"interaction_forward_uri":     m.InteractionForwardUri,
		"logging":                     m.Logging,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *interactiveClientConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_interactive_client_config"
}

func (r *interactiveClientConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaInteractiveClientConfigDataSource(ctx)
}

func (r *interactiveClientConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data interactiveClientConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "interactiveclientconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
