// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type providerGitHubDataSource struct{}

func NewProviderGitHub() datasource.DataSource {
	return &providerGitHubDataSource{}
}

type providerGitHubDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	AllowSignup  types.Bool   `tfsdk:"allow_signup"`
	Prompt       types.String `tfsdk:"prompt"`
	Display      types.String `tfsdk:"display"`
	Scope        types.String `tfsdk:"scope"`
	Type         types.String `tfsdk:"type"`
}

func (r *providerGitHubDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_git_hub"
}

func (r *providerGitHubDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderGitHubDataSource(ctx)
}

func (r *providerGitHubDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerGitHubDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderGitHubRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderGitHub(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderGitHub", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providergithub read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
