// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerLinkedInDataSource struct{}

func NewProviderLinkedIn() datasource.DataSource {
	return &providerLinkedInDataSource{}
}

type providerLinkedInDataSourceModel struct {
	ClientId             types.String `tfsdk:"client_id"`
	ClientSecret         types.String `tfsdk:"client_secret"`
	Scope                types.String `tfsdk:"scope"`
	IncludeGrantedScopes types.String `tfsdk:"include_granted_scopes"`
	Result               types.Object `tfsdk:"result"`
}

func (r *providerLinkedInDataSource) computeResult(ctx context.Context, m *providerLinkedInDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":                  types.StringType,
		"client_id":              m.ClientId.Type(ctx),
		"client_secret":          m.ClientSecret.Type(ctx),
		"include_granted_scopes": m.IncludeGrantedScopes.Type(ctx),
		"scope":                  m.Scope.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":                  types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderLinkedIn"),
		"client_id":              m.ClientId,
		"client_secret":          m.ClientSecret,
		"include_granted_scopes": m.IncludeGrantedScopes,
		"scope":                  m.Scope,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerLinkedInDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_linked_in"
}

func (r *providerLinkedInDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderLinkedInDataSource(ctx)
}

func (r *providerLinkedInDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerLinkedInDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providerlinkedin read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
