// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type audienceConfigDataSource struct{}

func NewAudienceConfig() datasource.DataSource {
	return &audienceConfigDataSource{}
}

type audienceConfigDataSourceModel struct {
	InteractionForwardUri    types.String `tfsdk:"interaction_forward_uri"`
	AccessTokenExpireSeconds types.Object `tfsdk:"access_token_expire_seconds"`
	Scopes                   types.Object `tfsdk:"scopes"`
	Cors                     types.Object `tfsdk:"cors"`
	Logging                  types.Object `tfsdk:"logging"`
	Type                     types.String `tfsdk:"type"`
}

func (r *audienceConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_audience_config"
}

func (r *audienceConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaAudienceConfigDataSource(ctx)
}

func (r *audienceConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data audienceConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetAudienceConfigRequest{Name: r.toName(data)}
	resp, err := r.client.GetAudienceConfig(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading AudienceConfig", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "audienceconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
