// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type interactiveClientConfigDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewInteractiveClientConfig() datasource.DataSource {
	return &interactiveClientConfigDataSource{}
}

type interactiveClientConfigDataSourceModel struct {
	InteractionForwardUri    types.String `tfsdk:"interaction_forward_uri"`
	AllowedRedirectUris      types.String `tfsdk:"allowed_redirect_uris"`
	AccessTokenExpireSeconds types.Object `tfsdk:"access_token_expire_seconds"`
	Cors                     types.Object `tfsdk:"cors"`
	Logging                  types.Object `tfsdk:"logging"`
}

func (r *interactiveClientConfigDataSource) toProto(m *interactiveClientConfigDataSourceModel) *v1alpha11.InteractiveClientConfig {
	return &v1alpha11.InteractiveClientConfig{
		AccessTokenExpireSeconds: nil,
		AllowedRedirectUris:      m.AllowedRedirectUris.ValueString(),
		Cors:                     nil,
		InteractionForwardUri:    m.InteractionForwardUri.ValueString(),
		Logging:                  nil,
	}
}

func (r *interactiveClientConfigDataSource) toModel(p *v1alpha11.InteractiveClientConfig, m *interactiveClientConfigDataSourceModel) {
	m.InteractionForwardUri = types.StringValue(p.InteractionForwardUri)
	m.AllowedRedirectUris = types.StringValue(p.AllowedRedirectUris)
}

func (r *interactiveClientConfigDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *interactiveClientConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_interactive_client_config"
}

func (r *interactiveClientConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{Attributes: map[string]schema.Attribute{"id": schema.StringAttribute{
		Description: "",
		Required:    true,
	}}}
}

func (r *interactiveClientConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data interactiveClientConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetInteractiveClientConfigRequest{Name: r.toName(data)}
	resp, err := r.client.GetInteractiveClientConfig(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading InteractiveClientConfig", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "interactiveclientconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
