// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type providerAuth0DataSource struct{}

func NewProviderAuth0() datasource.DataSource {
	return &providerAuth0DataSource{}
}

type providerAuth0DataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	TenantUrl    types.String `tfsdk:"tenant_url"`
	Type         types.String `tfsdk:"type"`
}

func (r *providerAuth0DataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_auth_0"
}

func (r *providerAuth0DataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderAuth0DataSource(ctx)
}

func (r *providerAuth0DataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerAuth0DataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderAuth0Request{Name: r.toName(data)}
	resp, err := r.client.GetProviderAuth0(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderAuth0", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerauth0 read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
