// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type providerOktaDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewProviderOkta() datasource.DataSource {
	return &providerOktaDataSource{}
}

type providerOktaDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	TenantUrl    types.String `tfsdk:"tenant_url"`
}

func (r *providerOktaDataSource) toProto(m *providerOktaDataSourceModel) *v1alpha11.ProviderOkta {
	return &v1alpha11.ProviderOkta{
		ClientId:     m.ClientId.ValueString(),
		ClientSecret: m.ClientSecret.ValueString(),
		Scope:        m.Scope.ValueString(),
		TenantUrl:    m.TenantUrl.ValueString(),
	}
}

func (r *providerOktaDataSource) toModel(p *v1alpha11.ProviderOkta, m *providerOktaDataSourceModel) {
	m.ClientId = types.StringValue(p.ClientId)
	m.ClientSecret = types.StringValue(p.ClientSecret)
	m.Scope = types.StringValue(p.Scope)
	m.TenantUrl = types.StringValue(p.TenantUrl)
}

func (r *providerOktaDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *providerOktaDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_okta"
}

func (r *providerOktaDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerOktaDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderOktaRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderOkta(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderOkta", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerokta read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
