// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type providerAuthwiseDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewProviderAuthwise() datasource.DataSource {
	return &providerAuthwiseDataSource{}
}

type providerAuthwiseDataSourceModel struct {
	Issuer   types.String `tfsdk:"issuer"`
	ClientId types.String `tfsdk:"client_id"`
}

func (r *providerAuthwiseDataSource) toProto(m *providerAuthwiseDataSourceModel) *v1alpha11.ProviderAuthwise {
	return &v1alpha11.ProviderAuthwise{
		ClientId: m.ClientId.ValueString(),
		Issuer:   m.Issuer.ValueString(),
	}
}

func (r *providerAuthwiseDataSource) toModel(p *v1alpha11.ProviderAuthwise, m *providerAuthwiseDataSourceModel) {
	m.Issuer = types.StringValue(p.Issuer)
	m.ClientId = types.StringValue(p.ClientId)
}

func (r *providerAuthwiseDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *providerAuthwiseDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_authwise"
}

func (r *providerAuthwiseDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerAuthwiseDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderAuthwiseRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderAuthwise(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderAuthwise", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerauthwise read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
