// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerFacebookDataSource struct{}

func NewProviderFacebook() datasource.DataSource {
	return &providerFacebookDataSource{}
}

type providerFacebookDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	UserFields   types.String `tfsdk:"user_fields"`
	Result       types.Object `tfsdk:"Result"`
}

func (r *providerFacebookDataSource) computeResult(ctx context.Context, m *providerFacebookDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":        types.StringType,
		"ClientId":     m.ClientId.Type(ctx),
		"ClientSecret": m.ClientSecret.Type(ctx),
		"Scope":        m.Scope.Type(ctx),
		"UserFields":   m.UserFields.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":        types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderFacebook"),
		"ClientId":     m.ClientId,
		"ClientSecret": m.ClientSecret,
		"Scope":        m.Scope,
		"UserFields":   m.UserFields,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerFacebookDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_facebook"
}

func (r *providerFacebookDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderFacebookDataSource(ctx)
}

func (r *providerFacebookDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerFacebookDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providerfacebook read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
