// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerLinkedInDataSource struct{}

func NewProviderLinkedIn() datasource.DataSource {
	return &providerLinkedInDataSource{}
}

type providerLinkedInDataSourceModel struct {
	ClientId             types.String         `tfsdk:"client_id"`
	ClientSecret         types.String         `tfsdk:"client_secret"`
	Scope                types.String         `tfsdk:"scope"`
	IncludeGrantedScopes types.String         `tfsdk:"include_granted_scopes"`
	Result               jsontypes.Normalized `tfsdk:"result"`
}

func (r *providerLinkedInDataSource) computeResult(ctx context.Context, m *providerLinkedInDataSourceModel) (*jsontypes.Normalized, error) {

	converted := map[string]any{
		"@type":                  "type.googleapis.com/authwise.types.core.v1alpha1.ProviderLinkedIn",
		"client_id":              m.ClientId.ValueString(),
		"client_secret":          m.ClientSecret.ValueString(),
		"include_granted_scopes": m.IncludeGrantedScopes.ValueString(),
		"scope":                  m.Scope.ValueString(),
	}
	j, err := json.Marshal(converted)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *providerLinkedInDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_linked_in"
}

func (r *providerLinkedInDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderLinkedInDataSource(ctx)
}

func (r *providerLinkedInDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerLinkedInDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "providerlinkedin read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
