// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerGitHubDataSource struct{}

func NewProviderGitHub() datasource.DataSource {
	return &providerGitHubDataSource{}
}

type providerGitHubDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	AllowSignup  types.Bool   `tfsdk:"allow_signup"`
	Prompt       types.String `tfsdk:"prompt"`
	Display      types.String `tfsdk:"display"`
	Scope        types.String `tfsdk:"scope"`
	Result       types.Object `tfsdk:"result"`
}

func (r *providerGitHubDataSource) computeResult(ctx context.Context, m *providerGitHubDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":         types.StringType,
		"allow_signup":  m.AllowSignup.Type(ctx),
		"client_id":     m.ClientId.Type(ctx),
		"client_secret": m.ClientSecret.Type(ctx),
		"display":       m.Display.Type(ctx),
		"prompt":        m.Prompt.Type(ctx),
		"scope":         m.Scope.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":         types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderGitHub"),
		"allow_signup":  m.AllowSignup,
		"client_id":     m.ClientId,
		"client_secret": m.ClientSecret,
		"display":       m.Display,
		"prompt":        m.Prompt,
		"scope":         m.Scope,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerGitHubDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_git_hub"
}

func (r *providerGitHubDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderGitHubDataSource(ctx)
}

func (r *providerGitHubDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerGitHubDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providergithub read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
