// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type providerLinkedInDataSource struct{}

func NewProviderLinkedIn() datasource.DataSource {
	return &providerLinkedInDataSource{}
}

type providerLinkedInDataSourceModel struct {
	ClientId             types.String `tfsdk:"client_id"`
	ClientSecret         types.String `tfsdk:"client_secret"`
	Scope                types.String `tfsdk:"scope"`
	IncludeGrantedScopes types.String `tfsdk:"include_granted_scopes"`
	Type                 types.String `tfsdk:"type"`
}

func (r *providerLinkedInDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_linked_in"
}

func (r *providerLinkedInDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderLinkedInDataSource(ctx)
}

func (r *providerLinkedInDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerLinkedInDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderLinkedInRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderLinkedIn(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderLinkedIn", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerlinkedin read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
