// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type providerAuthwiseDataSource struct{}

func NewProviderAuthwise() datasource.DataSource {
	return &providerAuthwiseDataSource{}
}

type providerAuthwiseDataSourceModel struct {
	Issuer   types.String `tfsdk:"issuer"`
	ClientId types.String `tfsdk:"client_id"`
	Type     types.String `tfsdk:"type"`
}

func (r *providerAuthwiseDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_authwise"
}

func (r *providerAuthwiseDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderAuthwiseDataSource(ctx)
}

func (r *providerAuthwiseDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerAuthwiseDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderAuthwiseRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderAuthwise(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderAuthwise", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerauthwise read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
