// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerAuthwiseDataSource struct{}

func NewProviderAuthwise() datasource.DataSource {
	return &providerAuthwiseDataSource{}
}

type providerAuthwiseDataSourceModel struct {
	Issuer   types.String `tfsdk:"issuer"`
	ClientId types.String `tfsdk:"client_id"`
	Result   types.Object `tfsdk:"result"`
}

func (r *providerAuthwiseDataSource) computeResult(ctx context.Context, m *providerAuthwiseDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":    types.StringType,
		"ClientId": m.ClientId.Type(ctx),
		"Issuer":   m.Issuer.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":    types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderAuthwise"),
		"ClientId": m.ClientId,
		"Issuer":   m.Issuer,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerAuthwiseDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_authwise"
}

func (r *providerAuthwiseDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderAuthwiseDataSource(ctx)
}

func (r *providerAuthwiseDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerAuthwiseDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providerauthwise read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
