// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type tenantUrlConfigDataSource struct{}

func NewTenantUrlConfig() datasource.DataSource {
	return &tenantUrlConfigDataSource{}
}

type tenantUrlConfigDataSourceModel struct {
	CookieDomain types.String         `tfsdk:"cookie_domain"`
	Result       jsontypes.Normalized `tfsdk:"result"`
}

func (r *tenantUrlConfigDataSource) computeResult(ctx context.Context, m *tenantUrlConfigDataSourceModel) (*jsontypes.Normalized, error) {
	j, err := json.Marshal(m)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *tenantUrlConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_tenant_url_config"
}

func (r *tenantUrlConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaTenantUrlConfigDataSource(ctx)
}

func (r *tenantUrlConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data tenantUrlConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "tenanturlconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
