// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerGoogleDataSource struct{}

func NewProviderGoogle() datasource.DataSource {
	return &providerGoogleDataSource{}
}

type providerGoogleDataSourceModel struct {
	ClientId     types.String         `tfsdk:"client_id"`
	ClientSecret types.String         `tfsdk:"client_secret"`
	Scope        types.String         `tfsdk:"scope"`
	Prompt       types.String         `tfsdk:"prompt"`
	Result       jsontypes.Normalized `tfsdk:"result"`
}

func (r *providerGoogleDataSource) computeResult(ctx context.Context, m *providerGoogleDataSourceModel) (*jsontypes.Normalized, error) {
	j, err := json.Marshal(m)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *providerGoogleDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_google"
}

func (r *providerGoogleDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderGoogleDataSource(ctx)
}

func (r *providerGoogleDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerGoogleDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "providergoogle read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
