// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerFacebookDataSource struct{}

func NewProviderFacebook() datasource.DataSource {
	return &providerFacebookDataSource{}
}

type providerFacebookDataSourceModel struct {
	ClientId     types.String         `tfsdk:"client_id"`
	ClientSecret types.String         `tfsdk:"client_secret"`
	Scope        types.String         `tfsdk:"scope"`
	UserFields   types.String         `tfsdk:"user_fields"`
	Result       jsontypes.Normalized `tfsdk:"result"`
}

func (r *providerFacebookDataSource) computeResult(ctx context.Context, m *providerFacebookDataSourceModel) (*jsontypes.Normalized, error) {
	j, err := json.Marshal(m)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *providerFacebookDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_facebook"
}

func (r *providerFacebookDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderFacebookDataSource(ctx)
}

func (r *providerFacebookDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerFacebookDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "providerfacebook read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
