// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerAuth0DataSource struct{}

func NewProviderAuth0() datasource.DataSource {
	return &providerAuth0DataSource{}
}

type providerAuth0DataSourceModel struct {
	ClientId     types.String         `tfsdk:"client_id"`
	ClientSecret types.String         `tfsdk:"client_secret"`
	Scope        types.String         `tfsdk:"scope"`
	TenantUrl    types.String         `tfsdk:"tenant_url"`
	Result       jsontypes.Normalized `tfsdk:"result"`
}

func (r *providerAuth0DataSource) computeResult(ctx context.Context, m *providerAuth0DataSourceModel) (*jsontypes.Normalized, error) {

	converted := map[string]any{
		"@type":         "type.googleapis.com/authwise.types.core.v1alpha1.ProviderAuth0",
		"client_id":     m.ClientId.ValueString(),
		"client_secret": m.ClientSecret.ValueString(),
		"scope":         m.Scope.ValueString(),
		"tenant_url":    m.TenantUrl.ValueString(),
	}
	j, err := json.Marshal(converted)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *providerAuth0DataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_auth_0"
}

func (r *providerAuth0DataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderAuth0DataSource(ctx)
}

func (r *providerAuth0DataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerAuth0DataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "providerauth0 read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
