// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerAuth0DataSource struct{}

func NewProviderAuth0() datasource.DataSource {
	return &providerAuth0DataSource{}
}

type providerAuth0DataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	TenantUrl    types.String `tfsdk:"tenant_url"`
	Result       types.Object `tfsdk:"Result"`
}

func (r *providerAuth0DataSource) computeResult(ctx context.Context, m *providerAuth0DataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":        types.StringType,
		"ClientId":     m.ClientId.Type(ctx),
		"ClientSecret": m.ClientSecret.Type(ctx),
		"Scope":        m.Scope.Type(ctx),
		"TenantUrl":    m.TenantUrl.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":        types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderAuth0"),
		"ClientId":     m.ClientId,
		"ClientSecret": m.ClientSecret,
		"Scope":        m.Scope,
		"TenantUrl":    m.TenantUrl,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerAuth0DataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_auth_0"
}

func (r *providerAuth0DataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderAuth0DataSource(ctx)
}

func (r *providerAuth0DataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerAuth0DataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providerauth0 read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
