// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	util "terraform-provider-authwise/internal/util"
)

type tenantConfigDataSource struct{}

func NewTenantConfig() datasource.DataSource {
	return &tenantConfigDataSource{}
}

type tenantConfigDataSourceModel struct {
	InteractionForwardUri    types.String         `tfsdk:"interaction_forward_uri"`
	AccessTokenExpireSeconds types.Int64          `tfsdk:"access_token_expire_seconds"`
	CookieDomain             types.String         `tfsdk:"cookie_domain"`
	Cors                     types.Object         `tfsdk:"cors"`
	Logging                  types.Object         `tfsdk:"logging"`
	Result                   jsontypes.Normalized `tfsdk:"result"`
}

func (r *tenantConfigDataSource) computeResult(ctx context.Context, m *tenantConfigDataSourceModel) (*jsontypes.Normalized, error) {
	converted_cors, err := util.ObjectToMap(m.Cors)
	if err != nil {
		return nil, err
	}
	converted_logging, err := util.ObjectToMap(m.Logging)
	if err != nil {
		return nil, err
	}

	converted := map[string]any{
		"@type":                       "type.googleapis.com/authwise.types.core.v1alpha1.TenantConfig",
		"access_token_expire_seconds": m.AccessTokenExpireSeconds.ValueInt64(),
		"cookie_domain":               m.CookieDomain.ValueString(),
		"cors":                        converted_cors,
		"interaction_forward_uri":     m.InteractionForwardUri.ValueString(),
		"logging":                     converted_logging,
	}
	j, err := json.Marshal(converted)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *tenantConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_tenant_config"
}

func (r *tenantConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaTenantConfigDataSource(ctx)
}

func (r *tenantConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data tenantConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "tenantconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
