// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type tenantConfigDataSource struct{}

func NewTenantConfig() datasource.DataSource {
	return &tenantConfigDataSource{}
}

type tenantConfigDataSourceModel struct {
	InteractionForwardUri    types.String `tfsdk:"interaction_forward_uri"`
	AccessTokenExpireSeconds types.Int64  `tfsdk:"access_token_expire_seconds"`
	CookieDomain             types.String `tfsdk:"cookie_domain"`
	Cors                     types.Object `tfsdk:"cors"`
	Logging                  types.Object `tfsdk:"logging"`
	Result                   types.Object `tfsdk:"result"`
}

func (r *tenantConfigDataSource) computeResult(ctx context.Context, m *tenantConfigDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":                    types.StringType,
		"AccessTokenExpireSeconds": m.AccessTokenExpireSeconds.Type(ctx),
		"CookieDomain":             m.CookieDomain.Type(ctx),
		"Cors":                     m.Cors.Type(ctx),
		"InteractionForwardUri":    m.InteractionForwardUri.Type(ctx),
		"Logging":                  m.Logging.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":                    types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.TenantConfig"),
		"AccessTokenExpireSeconds": m.AccessTokenExpireSeconds,
		"CookieDomain":             m.CookieDomain,
		"Cors":                     m.Cors,
		"InteractionForwardUri":    m.InteractionForwardUri,
		"Logging":                  m.Logging,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *tenantConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_tenant_config"
}

func (r *tenantConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaTenantConfigDataSource(ctx)
}

func (r *tenantConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data tenantConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "tenantconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
