// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerMicrosoftDataSource struct{}

func NewProviderMicrosoft() datasource.DataSource {
	return &providerMicrosoftDataSource{}
}

type providerMicrosoftDataSourceModel struct {
	Scope        types.String `tfsdk:"scope"`
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	PromptStyle  types.String `tfsdk:"prompt_style"`
	Tenant       types.String `tfsdk:"tenant"`
	Result       types.Object `tfsdk:"result"`
}

func (r *providerMicrosoftDataSource) computeResult(ctx context.Context, m *providerMicrosoftDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":        types.StringType,
		"ClientId":     m.ClientId.Type(ctx),
		"ClientSecret": m.ClientSecret.Type(ctx),
		"PromptStyle":  m.PromptStyle.Type(ctx),
		"Scope":        m.Scope.Type(ctx),
		"Tenant":       m.Tenant.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":        types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderMicrosoft"),
		"ClientId":     m.ClientId,
		"ClientSecret": m.ClientSecret,
		"PromptStyle":  m.PromptStyle,
		"Scope":        m.Scope,
		"Tenant":       m.Tenant,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerMicrosoftDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_microsoft"
}

func (r *providerMicrosoftDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderMicrosoftDataSource(ctx)
}

func (r *providerMicrosoftDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerMicrosoftDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providermicrosoft read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
