// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type providerUsernamePasswordDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewProviderUsernamePassword() datasource.DataSource {
	return &providerUsernamePasswordDataSource{}
}

type providerUsernamePasswordDataSourceModel struct {
	ForwardUri         types.String `tfsdk:"forward_uri"`
	PasswordHashType   types.String `tfsdk:"password_hash_type"`
	PasswordValidators types.Object `tfsdk:"password_validators"`
}

func (r *providerUsernamePasswordDataSource) toProto(m *providerUsernamePasswordDataSourceModel) *v1alpha11.ProviderUsernamePassword {
	return &v1alpha11.ProviderUsernamePassword{
		ForwardUri:         m.ForwardUri.ValueString(),
		PasswordHashType:   m.PasswordHashType.ValueString(),
		PasswordValidators: nil,
	}
}

func (r *providerUsernamePasswordDataSource) toModel(p *v1alpha11.ProviderUsernamePassword, m *providerUsernamePasswordDataSourceModel) {
	m.ForwardUri = types.StringValue(p.ForwardUri)
	m.PasswordHashType = types.StringValue(p.PasswordHashType)
}

func (r *providerUsernamePasswordDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *providerUsernamePasswordDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_username_password"
}

func (r *providerUsernamePasswordDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerUsernamePasswordDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderUsernamePasswordRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderUsernamePassword(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderUsernamePassword", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerusernamepassword read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
