// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type providerOktaDataSource struct{}

func NewProviderOkta() datasource.DataSource {
	return &providerOktaDataSource{}
}

type providerOktaDataSourceModel struct {
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Scope        types.String `tfsdk:"scope"`
	TenantUrl    types.String `tfsdk:"tenant_url"`
	Json         types.String `tfsdk:"json"`
}

func (r *providerOktaDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_okta"
}

func (r *providerOktaDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderOktaDataSource(ctx)
}

func (r *providerOktaDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerOktaDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderOktaRequest{Name: r.toName(data)}
	resp, err := r.client.GetProviderOkta(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading ProviderOkta", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "providerokta read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
