// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
)

type interactiveClientConfigDataSource struct{}

func NewInteractiveClientConfig() datasource.DataSource {
	return &interactiveClientConfigDataSource{}
}

type interactiveClientConfigDataSourceModel struct {
	InteractionForwardUri    types.String `tfsdk:"interaction_forward_uri"`
	AllowedRedirectUris      types.String `tfsdk:"allowed_redirect_uris"`
	AccessTokenExpireSeconds types.Object `tfsdk:"access_token_expire_seconds"`
	Cors                     types.Object `tfsdk:"cors"`
	Logging                  types.Object `tfsdk:"logging"`
	Type                     types.String `tfsdk:"type"`
}

func (r *interactiveClientConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_interactive_client_config"
}

func (r *interactiveClientConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaInteractiveClientConfigDataSource(ctx)
}

func (r *interactiveClientConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data interactiveClientConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetInteractiveClientConfigRequest{Name: r.toName(data)}
	resp, err := r.client.GetInteractiveClientConfig(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading InteractiveClientConfig", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "interactiveclientconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
