// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerUsernamePasswordDataSource struct{}

func NewProviderUsernamePassword() datasource.DataSource {
	return &providerUsernamePasswordDataSource{}
}

type providerUsernamePasswordDataSourceModel struct {
	ForwardUri         types.String         `tfsdk:"forward_uri"`
	PasswordHashType   types.String         `tfsdk:"password_hash_type"`
	PasswordValidators types.Object         `tfsdk:"password_validators"`
	Result             jsontypes.Normalized `tfsdk:"result"`
}

func (r *providerUsernamePasswordDataSource) computeResult(ctx context.Context, m *providerUsernamePasswordDataSourceModel) (*jsontypes.Normalized, error) {
	j, err := json.Marshal(m)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *providerUsernamePasswordDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_username_password"
}

func (r *providerUsernamePasswordDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderUsernamePasswordDataSource(ctx)
}

func (r *providerUsernamePasswordDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerUsernamePasswordDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "providerusernamepassword read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
