// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type providerUsernamePasswordDataSource struct{}

func NewProviderUsernamePassword() datasource.DataSource {
	return &providerUsernamePasswordDataSource{}
}

type providerUsernamePasswordDataSourceModel struct {
	ForwardUri         types.String `tfsdk:"forward_uri"`
	PasswordHashType   types.String `tfsdk:"password_hash_type"`
	PasswordValidators types.Object `tfsdk:"password_validators"`
	Result             types.Object `tfsdk:"result"`
}

func (r *providerUsernamePasswordDataSource) computeResult(ctx context.Context, m *providerUsernamePasswordDataSourceModel) (*types.Object, diag.Diagnostics) {
	tMap := map[string]attr.Type{
		"@type":              types.StringType,
		"ForwardUri":         m.ForwardUri.Type(ctx),
		"PasswordHashType":   m.PasswordHashType.Type(ctx),
		"PasswordValidators": m.PasswordValidators.Type(ctx),
	}
	vMap := map[string]attr.Value{
		"@type":              types.StringValue("type.googleapis.com/authwise.types.core.v1alpha1.ProviderUsernamePassword"),
		"ForwardUri":         m.ForwardUri,
		"PasswordHashType":   m.PasswordHashType,
		"PasswordValidators": m.PasswordValidators,
	}
	obj, diag := types.ObjectValue(tMap, vMap)

	if diag.HasError() {
		return nil, diag
	}

	return &obj, nil
}

func (r *providerUsernamePasswordDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider_username_password"
}

func (r *providerUsernamePasswordDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaProviderUsernamePasswordDataSource(ctx)
}

func (r *providerUsernamePasswordDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerUsernamePasswordDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, diag := r.computeResult(ctx, &data)
	if diag.HasError() {
		return
	}

	tflog.Trace(ctx, "providerusernamepassword read")

	response.Diagnostics.Append(response.State.Set(ctx, res)...)
}
