// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
)

type tenantConfigDataSource struct{}

func NewTenantConfig() datasource.DataSource {
	return &tenantConfigDataSource{}
}

type tenantConfigDataSourceModel struct {
	InteractionForwardUri    types.String         `tfsdk:"interaction_forward_uri"`
	AccessTokenExpireSeconds types.Int64          `tfsdk:"access_token_expire_seconds"`
	CookieDomain             types.String         `tfsdk:"cookie_domain"`
	Cors                     types.Object         `tfsdk:"cors"`
	Logging                  types.Object         `tfsdk:"logging"`
	Result                   jsontypes.Normalized `tfsdk:"result"`
}

func (r *tenantConfigDataSource) computeResult(ctx context.Context, m *tenantConfigDataSourceModel) (*jsontypes.Normalized, error) {
	j, err := json.Marshal(m)

	if err != nil {
		return nil, err
	}

	val := jsontypes.NewNormalizedValue(string(j))
	return &val, nil
}

func (r *tenantConfigDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_tenant_config"
}

func (r *tenantConfigDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = GenSchemaTenantConfigDataSource(ctx)
}

func (r *tenantConfigDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data tenantConfigDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	res, err := r.computeResult(ctx, &data)
	if err != nil {
		return
	}
	data.Result = *res
	tflog.Trace(ctx, "tenantconfig read")

	response.Diagnostics.Append(response.State.Set(ctx, data)...)
}
