// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type eventResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewEvent() resource.Resource {
	return &eventResource{}
}

type eventModel struct {
	Id            types.String `tfsdk:"id"`
	TenantId      types.String `tfsdk:"tenant_id"`
	RequestId     types.String `tfsdk:"request_id"`
	ClientId      types.String `tfsdk:"client_id"`
	RealmId       types.String `tfsdk:"realm_id"`
	UserId        types.String `tfsdk:"user_id"`
	SessionId     types.String `tfsdk:"session_id"`
	InteractionId types.String `tfsdk:"interaction_id"`
	EventType     types.String `tfsdk:"event_type"`
	EventMessage  types.String `tfsdk:"event_message"`
	StartState    types.String `tfsdk:"start_state"`
	EndState      types.String `tfsdk:"end_state"`
	StartTime     types.Object `tfsdk:"start_time"`
	EndTime       types.Object `tfsdk:"end_time"`
	Attributes    types.Object `tfsdk:"attributes"`
	CreatedAt     types.Object `tfsdk:"created_at"`
}

func (r *eventResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *eventResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_event"
}

func (r *eventResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaEvent(ctx)
}

func (r *eventResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data v1alpha11.Event

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	cr := &v1alpha1.CreateEventRequest{}
}

func (r *eventResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (r *eventResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (r *eventResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
