// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type eventResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewEvent() resource.Resource {
	return &eventResource{}
}

type eventModel struct {
	Id            types.String `tfsdk:"id"`
	TenantId      types.String `tfsdk:"tenant_id"`
	RequestId     types.String `tfsdk:"request_id"`
	ClientId      types.String `tfsdk:"client_id"`
	RealmId       types.String `tfsdk:"realm_id"`
	UserId        types.String `tfsdk:"user_id"`
	SessionId     types.String `tfsdk:"session_id"`
	InteractionId types.String `tfsdk:"interaction_id"`
	EventType     types.String `tfsdk:"event_type"`
	EventMessage  types.String `tfsdk:"event_message"`
	StartState    types.String `tfsdk:"start_state"`
	EndState      types.String `tfsdk:"end_state"`
	StartTime     types.Object `tfsdk:"start_time"`
	EndTime       types.Object `tfsdk:"end_time"`
	Attributes    types.Object `tfsdk:"attributes"`
	CreatedAt     types.Object `tfsdk:"created_at"`
}

func (r *eventResource) toName(data eventModel) string {
	return fmt.Sprintf("events/%s", data.Id.ValueString())
}
func (r *eventResource) toProto(m *eventModel) *v1alpha11.Event {
	return &v1alpha11.Event{
		Attributes:    nil,
		ClientId:      m.ClientId.ValueString(),
		CreatedAt:     nil,
		EndState:      m.EndState.ValueString(),
		EndTime:       nil,
		EventMessage:  m.EventMessage.ValueString(),
		EventType:     m.EventType.ValueString(),
		Id:            m.Id.ValueString(),
		InteractionId: m.InteractionId.ValueString(),
		RealmId:       m.RealmId.ValueString(),
		RequestId:     m.RequestId.ValueString(),
		SessionId:     m.SessionId.ValueString(),
		StartState:    m.StartState.ValueString(),
		StartTime:     nil,
		TenantId:      m.TenantId.ValueString(),
		UserId:        m.UserId.ValueString(),
	}
}

func (r *eventResource) toModel(p *v1alpha11.Event, m *eventModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.RequestId = types.StringValue(p.RequestId)
	m.ClientId = types.StringValue(p.ClientId)
	m.RealmId = types.StringValue(p.RealmId)
	m.UserId = types.StringValue(p.UserId)
	m.SessionId = types.StringValue(p.SessionId)
	m.InteractionId = types.StringValue(p.InteractionId)
	m.EventType = types.StringValue(p.EventType)
	m.EventMessage = types.StringValue(p.EventMessage)
	m.StartState = types.StringValue(p.StartState)
	m.EndState = types.StringValue(p.EndState)
}

func (r *eventResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *eventResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_event"
}

func (r *eventResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaEvent(ctx)
}

func (r *eventResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data eventModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.CreateEventRequest{Event: r.toProto(&data)}
	resp, err := r.client.CreateEvent(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Event", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "event create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *eventResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data eventModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetEventRequest{Name: r.toName(data)}
	resp, err := r.client.GetEvent(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Event", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "event read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *eventResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data eventModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.UpdateEventRequest{
		Event: r.toProto(&data),
		Name:  r.toName(data),
	}
	resp, err := r.client.UpdateEvent(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Event", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "event update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *eventResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data eventModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteEventRequest{Name: r.toName(data)}
	_, err := r.client.DeleteEvent(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Event", err.Error())
		return
	}
	return
}
