// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

type permissionResource struct{}

func NewPermission() resource.Resource {
	return &permissionResource{}
}

type permissionModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Name       types.String `tfsdk:"name"`
}

func (*permissionResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_permission"
}

func (*permissionResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaPermission(ctx)
}

func (*permissionResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data permissionModel
	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)
	if response.Diagnostics.HasError() {
		return
	}
}

func (*permissionResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (*permissionResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (*permissionResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
