// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type permissionResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewPermission() resource.Resource {
	return &permissionResource{}
}

type permissionModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Name       types.String `tfsdk:"name"`
}

func (r *permissionResource) toName(data permissionModel) string {
	return fmt.Sprintf("audiences/%s/permissions/%s", data.AudienceId.ValueString(), data.Id.ValueString())
}
func (r *permissionResource) toProto(m *permissionModel) (*v1alpha11.Permission, error) {
	return &v1alpha11.Permission{
		AudienceId: m.AudienceId.ValueString(),
		Id:         m.Id.ValueString(),
		Name:       m.Name.ValueString(),
	}, nil
}

func (r *permissionResource) toModel(p *v1alpha11.Permission, m *permissionModel) error {
	m.Id = types.StringValue(p.Id)
	m.AudienceId = types.StringValue(p.AudienceId)
	m.Name = types.StringValue(p.Name)
	return nil
}

func (r *permissionResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *permissionResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_permission"
}

func (r *permissionResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaPermission(ctx)
}

func (r *permissionResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data permissionModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Permission to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreatePermissionRequest{Permission: val}
	resp, err := r.client.CreatePermission(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Permission", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Permission to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "permission create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *permissionResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data permissionModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetPermissionRequest{Name: r.toName(data)}
	resp, err := r.client.GetPermission(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Permission", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Permission to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "permission read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *permissionResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data permissionModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Permission to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdatePermissionRequest{
		Name:       r.toName(data),
		Permission: val,
	}
	resp, err := r.client.UpdatePermission(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Permission", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Permission to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "permission update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *permissionResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data permissionModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeletePermissionRequest{Name: r.toName(data)}
	_, err := r.client.DeletePermission(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Permission", err.Error())
		return
	}
	return
}
