package provider

import (
	"context"
	"crypto/tls"
	"os"

	tfruntime "github.com/activatedio/tfinfra/pkg/tf"
	"github.com/authwisecom/api-client-go/authwise"
	identitypb "github.com/authwisecom/api-client-go/authwise/identity/v1alpha1"
	"github.com/authwisecom/api-client-go/credentials/bearer"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"

	"terraform-provider-authwise/internal/generated"
)

var _ provider.Provider = &AuthwiseProvider{}

// AuthwiseProvider manages Authwise identity objects over the published
// gRPC API. All resources and data sources are generated by tfinfra from
// the spec table in gen/main.go.
type AuthwiseProvider struct {
	// version is set to the provider version on release, "dev" when built
	// locally, and "test" in acceptance testing.
	version string
}

type authwiseProviderModel struct {
	Endpoint     types.String `tfsdk:"endpoint"`
	TokenUrl     types.String `tfsdk:"token_url"`
	ClientId     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Audience     types.String `tfsdk:"audience"`
	Insecure     types.Bool   `tfsdk:"insecure"`

	// Scope identifier defaults; per-resource attributes override them.
	TenantId   types.String `tfsdk:"tenant_id"`
	IssuerId   types.String `tfsdk:"issuer_id"`
	RealmId    types.String `tfsdk:"realm_id"`
	AudienceId types.String `tfsdk:"audience_id"`
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &AuthwiseProvider{version: version}
	}
}

func (p *AuthwiseProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "authwise"
	resp.Version = p.version
}

func (p *AuthwiseProvider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages Authwise identity objects over the published gRPC API.",
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "gRPC API endpoint, e.g. `api.example.authwise.io:443`. Falls back to `AUTHWISE_ENDPOINT`.",
			},
			"token_url": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "OAuth2 token endpoint for the client_credentials grant, e.g. `https://auth.example.authwise.io/oauth/token`. Falls back to `AUTHWISE_TOKEN_URL`. When unset (with `client_id`), the provider uses the local awctl credential store instead.",
			},
			"client_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "OAuth2 client ID for the client_credentials grant. Falls back to `AUTHWISE_CLIENT_ID`.",
			},
			"client_secret": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "OAuth2 client secret. Falls back to `AUTHWISE_CLIENT_SECRET`.",
			},
			"audience": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "OAuth2 audience passed to the token endpoint. Falls back to `AUTHWISE_AUDIENCE`.",
			},
			"insecure": schema.BoolAttribute{
				Optional:            true,
				MarkdownDescription: "Use plaintext gRPC (development only).",
			},
			"tenant_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default tenant identifier used to compose AIP parents; per-resource `tenant_id` attributes override it.",
			},
			"issuer_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default issuer identifier; per-resource `issuer_id` attributes override it.",
			},
			"realm_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default realm identifier; per-resource `realm_id` attributes override it.",
			},
			"audience_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default audience identifier; per-resource `audience_id` attributes override it.",
			},
		},
	}
}

// stringOr returns the attribute value, falling back to the environment
// variable when the attribute is null or unknown.
func stringOr(v types.String, env string) string {
	if !v.IsNull() && !v.IsUnknown() {
		return v.ValueString()
	}
	return os.Getenv(env)
}

func (p *AuthwiseProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {

	var config authwiseProviderModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	endpoint := stringOr(config.Endpoint, "AUTHWISE_ENDPOINT")
	if endpoint == "" {
		resp.Diagnostics.AddAttributeError(path.Root("endpoint"),
			"missing endpoint",
			"set the endpoint attribute or the AUTHWISE_ENDPOINT environment variable")
		return
	}

	tokenURL := stringOr(config.TokenUrl, "AUTHWISE_TOKEN_URL")
	clientID := stringOr(config.ClientId, "AUTHWISE_CLIENT_ID")
	clientSecret := stringOr(config.ClientSecret, "AUTHWISE_CLIENT_SECRET")

	var bearerService bearer.Service
	if clientID != "" {
		if tokenURL == "" || clientSecret == "" {
			resp.Diagnostics.AddAttributeError(path.Root("client_id"),
				"incomplete client_credentials configuration",
				"client_id is set, so token_url and client_secret are required (attributes or AUTHWISE_TOKEN_URL / AUTHWISE_CLIENT_SECRET)")
			return
		}
		bearerService = bearer.NewClientCredentialsService(bearer.ClientCredentialsParams{
			TokenURL:     tokenURL,
			ClientID:     clientID,
			ClientSecret: clientSecret,
			Audience:     stringOr(config.Audience, "AUTHWISE_AUDIENCE"),
		})
	} else {
		// Development fallback: the local awctl credential store.
		bearerService = bearer.NewDefaultService()
	}

	transport := credentials.NewTLS(&tls.Config{MinVersion: tls.VersionTLS12})
	if config.Insecure.ValueBool() {
		transport = insecure.NewCredentials()
	}

	conn, err := grpc.NewClient(endpoint,
		grpc.WithTransportCredentials(transport),
		grpc.WithUnaryInterceptor(authwise.NewBearerCredentialsInterceptor(bearerService)),
	)
	if err != nil {
		resp.Diagnostics.AddError("cannot create gRPC client", err.Error())
		return
	}

	defaults := map[string]string{}
	for attr, v := range map[string]types.String{
		"tenant_id":   config.TenantId,
		"issuer_id":   config.IssuerId,
		"realm_id":    config.RealmId,
		"audience_id": config.AudienceId,
	} {
		if !v.IsNull() && !v.IsUnknown() {
			defaults[attr] = v.ValueString()
		}
	}

	providerData := &tfruntime.ProviderData{
		Clients: map[string]any{
			"identity": identitypb.NewAuthwiseIdentityServiceClient(conn),
		},
		Defaults: defaults,
	}

	resp.ResourceData = providerData
	resp.DataSourceData = providerData
}

func (p *AuthwiseProvider) Resources(_ context.Context) []func() resource.Resource {
	return generated.Resources()
}

func (p *AuthwiseProvider) DataSources(_ context.Context) []func() datasource.DataSource {
	return generated.DataSources()
}
