// Package provider wires the tfinfra-generated Authwise surface into a
// Terraform Plugin Framework provider: configuration, authentication, and
// registration.
package provider

import (
	"context"
	"crypto/tls"
	"fmt"
	"os"

	"git.authwise.com/authwise/api-client-support/authwise"
	supportcreds "git.authwise.com/authwise/api-client-support/credentials"
	"git.authwise.com/authwise/api-client-support/credentials/bearer"
	accesspb "git.authwise.com/authwise/apis/authwise/access/v1alpha1"
	guardpb "git.authwise.com/authwise/apis/authwise/guardcontrol/v1alpha1"
	identitypb "git.authwise.com/authwise/apis/authwise/identity/v1alpha1"
	"git.authwise.com/authwise/terraform-provider-authwise/internal/generated"
	tfruntime "github.com/activatedio/tfinfra/pkg/tf"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"
)

// tenantIDAttribute is the tenant scope attribute: the provider default and
// the per-resource override the hand-written resources compose names from.
const tenantIDAttribute = "tenant_id"

var _ provider.Provider = &AuthwiseProvider{}

// AuthwiseProvider manages Authwise identity objects over the published
// gRPC API. Most resources and data sources are generated by tfinfra from
// the spec table in gen/main.go; the rest are hand-written in this package
// (authwise_secret, authwise_realm_authentication_policy) or wrap a
// generated one (authwise_access_binding, authwise_realm).
type AuthwiseProvider struct {
	// version is set to the provider version on release, "dev" when built
	// locally, and "test" in acceptance testing.
	version string
}

type authwiseProviderModel struct {
	Endpoint      types.String `tfsdk:"endpoint"`
	GuardEndpoint types.String `tfsdk:"guard_endpoint"`
	TokenURL      types.String `tfsdk:"token_url"`
	ClientID      types.String `tfsdk:"client_id"`
	ClientSecret  types.String `tfsdk:"client_secret"`
	Audience      types.String `tfsdk:"audience"`
	Insecure      types.Bool   `tfsdk:"insecure"`

	// Scope identifier defaults; per-resource attributes override them.
	TenantID   types.String `tfsdk:"tenant_id"`
	IssuerID   types.String `tfsdk:"issuer_id"`
	RealmID    types.String `tfsdk:"realm_id"`
	AudienceID types.String `tfsdk:"audience_id"`
}

// New returns the provider factory, stamped with the release version.
func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &AuthwiseProvider{version: version}
	}
}

// providerTypeName prefixes every resource and data source type.
const providerTypeName = "authwise"

// Metadata implements provider.Provider.
func (p *AuthwiseProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = providerTypeName
	resp.Version = p.version
}

// Schema implements provider.Provider.
func (p *AuthwiseProvider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages Authwise identity objects over the published gRPC API.",
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "gRPC API endpoint, e.g. `api.example.authwise.io:443`. Falls back to `AUTHWISE_ENDPOINT`.",
			},
			"guard_endpoint": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "guard-control's gRPC endpoint, e.g. `guard.example.authwise.io:443`, for the `authwise_guard_*` resources and data sources. Falls back to `AUTHWISE_GUARD_ENDPOINT`. It takes the same credentials as `endpoint`. Unset, a Guard resource fails at plan.",
			},
			"token_url": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "OAuth2 token endpoint for the client_credentials grant, e.g. `https://auth.example.authwise.io/oauth/token`. Falls back to `AUTHWISE_TOKEN_URL`. When unset (with `client_id`), the provider uses the local awctl credential store instead.",
			},
			"client_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "OAuth2 client ID for the client_credentials grant. Falls back to `AUTHWISE_CLIENT_ID`.",
			},
			"client_secret": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "OAuth2 client secret. Falls back to `AUTHWISE_CLIENT_SECRET`.",
			},
			"audience": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "OAuth2 audience passed to the token endpoint. Falls back to `AUTHWISE_AUDIENCE`.",
			},
			"insecure": schema.BoolAttribute{
				Optional:            true,
				MarkdownDescription: "Use plaintext gRPC (development only).",
			},
			// The defaults are ids, validated like the per-resource
			// attributes they stand in for.
			"tenant_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default tenant identifier used to compose AIP parents; per-resource `tenant_id` attributes override it.",
				Validators:          []validator.String{tfruntime.ReferenceID("t", "tenant", "")},
			},
			"issuer_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default issuer identifier; per-resource `issuer_id` attributes override it.",
				Validators:          []validator.String{tfruntime.ReferenceID("i", "issuer", "authwise_issuer.<name>.issuer_id")},
			},
			"realm_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default realm identifier; per-resource `realm_id` attributes override it.",
				Validators:          []validator.String{tfruntime.ReferenceID("r", "realm", "authwise_realm.<name>.realm_id")},
			},
			"audience_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Default audience identifier; per-resource `audience_id` attributes override it.",
				Validators:          []validator.String{tfruntime.ReferenceID("a", "audience", "authwise_audience.<name>.audience_id")},
			},
		},
	}
}

// bearerServiceFor selects the token source via the shared support
// library: the client_credentials grant when fully configured, otherwise
// the local awctl credential store as the development fallback. Partial
// client credentials are an error naming the gaps.
func bearerServiceFor(config authwiseProviderModel) (bearer.Service, error) {

	svc, err := supportcreds.Select(supportcreds.SelectParams{
		TokenURL:     stringOr(config.TokenURL, "AUTHWISE_TOKEN_URL"),
		ClientID:     stringOr(config.ClientID, "AUTHWISE_CLIENT_ID"),
		ClientSecret: stringOr(config.ClientSecret, "AUTHWISE_CLIENT_SECRET"),
		Audience:     stringOr(config.Audience, "AUTHWISE_AUDIENCE"),
		Hint:         "no valid credentials: run `awctl auth login` for the local development store, or set token_url, client_id, and client_secret (or the AUTHWISE_TOKEN_URL / AUTHWISE_CLIENT_ID / AUTHWISE_CLIENT_SECRET environment variables)",
	})
	if err != nil {
		return nil, fmt.Errorf("%w; set the provider attributes or the AUTHWISE_* environment variables", err)
	}
	return svc, nil
}

// stringOr returns the attribute value, falling back to the environment
// variable when the attribute is null or unknown.
func stringOr(v types.String, env string) string {
	if !v.IsNull() && !v.IsUnknown() {
		return v.ValueString()
	}
	return os.Getenv(env)
}

// Configure implements provider.Provider: it builds the authenticated gRPC
// client and hands tf.ProviderData to every generated resource and data
// source.
func (p *AuthwiseProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {

	var config authwiseProviderModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	endpoint := stringOr(config.Endpoint, "AUTHWISE_ENDPOINT")
	if endpoint == "" {
		resp.Diagnostics.AddAttributeError(path.Root("endpoint"),
			"missing endpoint",
			"set the endpoint attribute or the AUTHWISE_ENDPOINT environment variable")
		return
	}

	bearerService, err := bearerServiceFor(config)
	if err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("client_id"),
			"incomplete client_credentials configuration", err.Error())
		return
	}

	transport := credentials.NewTLS(&tls.Config{MinVersion: tls.VersionTLS12})
	if config.Insecure.ValueBool() {
		transport = insecure.NewCredentials()
	}

	dial := func(target string) (*grpc.ClientConn, error) {
		return grpc.NewClient(target,
			grpc.WithTransportCredentials(transport),
			grpc.WithChainUnaryInterceptor(
				authwise.NewBearerCredentialsInterceptor(bearerService),
				warningInterceptor,
			),
		)
	}

	conn, err := dial(endpoint)
	if err != nil {
		resp.Diagnostics.AddError("cannot create gRPC client", err.Error())
		return
	}

	guardConn, guardConfigured, err := guardConnFor(config, dial)
	if err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("guard_endpoint"), "cannot create guard-control gRPC client", err.Error())
		return
	}

	defaults := map[string]string{}
	for attr, v := range map[string]types.String{
		"tenant_id":   config.TenantID,
		"issuer_id":   config.IssuerID,
		"realm_id":    config.RealmID,
		"audience_id": config.AudienceID,
	} {
		if !v.IsNull() && !v.IsUnknown() {
			defaults[attr] = v.ValueString()
		}
	}

	providerData := &tfruntime.ProviderData{
		Clients: map[string]any{
			"identity": userContactClient{newAppearanceDefaultClient(identitypb.NewAuthwiseIdentityServiceClient(conn))},
			"access":   accesspb.NewAuthwiseAccessServiceClient(conn),

			guardClientKey:            guardpb.NewGuardControlServiceClient(guardConn),
			guardTenantAdminClientKey: guardpb.NewGuardTenantAdminServiceClient(guardConn),
			guardNodeClientKey:        guardpb.NewGuardNodeServiceClient(guardConn),
			guardConfiguredKey:        guardConfigured,
		},
		Defaults: defaults,
	}

	resp.ResourceData = providerData
	resp.DataSourceData = providerData
}

// Resources implements provider.Provider with the generated constructors,
// substituting the hand-written wrappers that add behavior the generator does
// not express, plus the resources whose shapes are beyond it.
func (p *AuthwiseProvider) Resources(ctx context.Context) []func() resource.Resource {
	return guardWrap(ctx, append(substitute(ctx, generated.Resources(), map[string]func() resource.Resource{
		accessBindingTypeName:     newAccessBindingResource,
		realmTypeName:             newRealmResource,
		factorTypeName:            newFactorResource,
		appearanceProfileTypeName: newAppearanceProfileResource,
		guardTenantTypeName:       newGuardTenantResource,
		guardInviteTypeName:       newGuardInviteResource,
		guardNodeTypeName:         newGuardNodeResource,
	}),
		newSecretResource,
		newRealmAuthenticationPolicyResource,
		newAssetContentResource,
		newGuardNodeGrantsResource,
	))
}

// substitute replaces generated constructors with wrappers, matched on the
// Terraform type name each resource reports rather than on list position.
func substitute(ctx context.Context, generated []func() resource.Resource, wrappers map[string]func() resource.Resource) []func() resource.Resource {

	out := make([]func() resource.Resource, 0, len(generated))

	for _, factory := range generated {
		resp := &resource.MetadataResponse{}
		factory().Metadata(ctx, resource.MetadataRequest{ProviderTypeName: providerTypeName}, resp)
		if w, ok := wrappers[resp.TypeName]; ok {
			factory = w
		}
		out = append(out, factory)
	}

	return out
}

// factorTypeName is the Terraform type of the generated factor resource,
// wrapped to report kit's warnings.
const factorTypeName = "authwise_factor"

func newFactorResource() resource.Resource {
	return &warningResource{inner: generated.NewFactorResource()}
}

// DataSources implements provider.Provider with the generated constructors
// plus the hand-written ones.
func (p *AuthwiseProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return guardDataSourceWrap(ctx, append(generated.DataSources(), newSecretDataSource, newRealmAuthenticationContextSchemaDataSource))
}
