// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
	util "terraform-provider-authwise/internal/util"
)

type providerResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewProvider() resource.Resource {
	return &providerResource{}
}

type providerModel struct {
	Id           types.String `tfsdk:"id"`
	RealmId      types.String `tfsdk:"realm_id"`
	Name         types.String `tfsdk:"name"`
	ProviderType types.String `tfsdk:"provider_type"`
	Config       types.Object `tfsdk:"config"`
}

func (r *providerResource) toName(data providerModel) string {
	return fmt.Sprintf("providers/%s", data.Id.ValueString())
}
func (r *providerResource) toProto(m *providerModel) (*v1alpha11.Provider, error) {
	converted_config, err := util.ObjectToProtoAny(m.Config)
	if err != nil {
		return nil, err
	}
	return &v1alpha11.Provider{
		Config:       converted_config,
		Id:           m.Id.ValueString(),
		Name:         m.Name.ValueString(),
		ProviderType: m.ProviderType.ValueString(),
		RealmId:      m.RealmId.ValueString(),
	}, nil
}

func (r *providerResource) toModel(p *v1alpha11.Provider, m *providerModel) error {
	m.Id = types.StringValue(p.Id)
	m.RealmId = types.StringValue(p.RealmId)
	m.Name = types.StringValue(p.Name)
	m.ProviderType = types.StringValue(p.ProviderType)
	converted_config, err := util.ProtoAnyToObject(p.Config)
	if err != nil {
		return err
	}
	m.Config = *converted_config
	return nil
}

func (r *providerResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *providerResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider"
}

func (r *providerResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaProvider(ctx)
}

func (r *providerResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data providerModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Provider to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreateProviderRequest{Provider: val}
	resp, err := r.client.CreateProvider(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Provider", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Provider to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "provider create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *providerResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data providerModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderRequest{Name: r.toName(data)}
	resp, err := r.client.GetProvider(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Provider", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Provider to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "provider read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *providerResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data providerModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Provider to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdateProviderRequest{
		Name:     r.toName(data),
		Provider: val,
	}
	resp, err := r.client.UpdateProvider(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Provider", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Provider to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "provider update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *providerResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data providerModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteProviderRequest{Name: r.toName(data)}
	_, err := r.client.DeleteProvider(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Provider", err.Error())
		return
	}
	return
}
