// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type providerDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewProviderDataSource() datasource.DataSource {
	return &providerDataSource{}
}

func (r *providerDataSource) toModel(p *v1alpha11.Provider, m *providerDataSourceModel) {
	m.Id = types.StringValue(p.Id)
	m.RealmId = types.StringValue(p.RealmId)
	m.Name = types.StringValue(p.Name)
	m.ProviderType = types.StringValue(p.ProviderType)
}

type providerDataSourceModel struct {
	Id           types.String `tfsdk:"id"`
	RealmId      types.String `tfsdk:"realm_id"`
	Name         types.String `tfsdk:"name"`
	ProviderType types.String `tfsdk:"provider_type"`
	Config       types.Object `tfsdk:"config"`
}

func (r *providerDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *providerDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider"
}

func (r *providerDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data providerDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetProviderRequest{Name: r.toName(data)}
	resp, err := r.client.GetProvider(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Provider", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "provider read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
