// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

type providerResource struct{}

func NewProvider() resource.Resource {
	return &providerResource{}
}

type providerModel struct {
	Id           types.String `tfsdk:"id"`
	RealmId      types.String `tfsdk:"realm_id"`
	Name         types.String `tfsdk:"name"`
	ProviderType types.String `tfsdk:"provider_type"`
	Config       types.Object `tfsdk:"config"`
}

func (*providerResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_provider"
}

func (*providerResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaProvider(ctx)
}

func (*providerResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data providerModel
	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)
	if response.Diagnostics.HasError() {
		return
	}
}

func (*providerResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (*providerResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (*providerResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
