// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

type realmResource struct{}

func NewRealm() resource.Resource {
	return &realmResource{}
}

type realmModel struct {
	Id               types.String `tfsdk:"id"`
	TenantId         types.String `tfsdk:"tenant_id"`
	UserDatabaseType types.String `tfsdk:"user_database_type"`
	Name             types.String `tfsdk:"name"`
	Description      types.String `tfsdk:"description"`
}

func (*realmResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_realm"
}

func (*realmResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaRealm(ctx)
}

func (*realmResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data realmModel
	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)
	if response.Diagnostics.HasError() {
		return
	}
}

func (*realmResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (*realmResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (*realmResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
