// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type realmResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewRealm() resource.Resource {
	return &realmResource{}
}

type realmModel struct {
	Id               types.String `tfsdk:"id"`
	TenantId         types.String `tfsdk:"tenant_id"`
	UserDatabaseType types.String `tfsdk:"user_database_type"`
	Name             types.String `tfsdk:"name"`
	Description      types.String `tfsdk:"description"`
}

func (r *realmResource) toProto(m *realmModel) *v1alpha11.Realm {
	return &v1alpha11.Realm{
		Description:      m.Description.ValueString(),
		Id:               m.Id.ValueString(),
		Name:             m.Name.ValueString(),
		TenantId:         m.TenantId.ValueString(),
		UserDatabaseType: m.UserDatabaseType.ValueString(),
	}
}

func (r *realmResource) toModel(p *v1alpha11.Realm, m *realmModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.UserDatabaseType = types.StringValue(p.UserDatabaseType)
	m.Name = types.StringValue(p.Name)
	m.Description = types.StringValue(p.Description)
}

func (r *realmResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *realmResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_realm"
}

func (r *realmResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaRealm(ctx)
}

func (r *realmResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data realmModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	cr := &v1alpha1.CreateRealmRequest{Realm: r.toProto(&data)}
	resp, err := r.client.CreateRealm(ctx, cr)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Realm", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "realm create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *realmResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (r *realmResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (r *realmResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
