// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type roleResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewRole() resource.Resource {
	return &roleResource{}
}

type roleModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Name       types.String `tfsdk:"name"`
	Auto       types.Bool   `tfsdk:"auto"`
}

func (r *roleResource) toProto(m *roleModel) *v1alpha11.Role {
	return &v1alpha11.Role{
		AudienceId: m.AudienceId.ValueString(),
		Auto:       m.Auto.ValueBool(),
		Id:         m.Id.ValueString(),
		Name:       m.Name.ValueString(),
	}
}

func (r *roleResource) toModel(p *v1alpha11.Role, m *roleModel) {
	m.Id = types.StringValue(p.Id)
	m.AudienceId = types.StringValue(p.AudienceId)
	m.Name = types.StringValue(p.Name)
	m.Auto = types.BoolValue(p.Auto)
}

func (r *roleResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *roleResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_role"
}

func (r *roleResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaRole(ctx)
}

func (r *roleResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data roleModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	cr := &v1alpha1.CreateRoleRequest{Role: r.toProto(&data)}
	resp, err := r.client.CreateRole(ctx, cr)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Role", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "role create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *roleResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (r *roleResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (r *roleResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
