// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

type roleResource struct{}

func NewRole() resource.Resource {
	return &roleResource{}
}

type roleModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Name       types.String `tfsdk:"name"`
	Auto       types.Bool   `tfsdk:"auto"`
}

func (*roleResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_role"
}

func (*roleResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaRole(ctx)
}

func (*roleResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data roleModel
	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)
	if response.Diagnostics.HasError() {
		return
	}
}

func (*roleResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
}

func (*roleResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
}

func (*roleResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
}
