// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// GenSchemaInteractiveClientConfig returns tfsdk.Schema definition for InteractiveClientConfig
func GenSchemaInteractiveClientConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"allowed_redirect_uris": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantConfig returns tfsdk.Schema definition for TenantConfig
func GenSchemaTenantConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"cookie_domain": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantUrlConfig returns tfsdk.Schema definition for TenantUrlConfig
func GenSchemaTenantUrlConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{"cookie_domain": schema.StringAttribute{
		Description: "",
		Optional:    true,
	}}}
}

// GenSchemaAudienceConfig returns tfsdk.Schema definition for AudienceConfig
func GenSchemaAudienceConfig(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"scopes": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"authorization": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"include_permissions": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"include_roles": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"openid": schema.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderAuthwise returns tfsdk.Schema definition for ProviderAuthwise
func GenSchemaProviderAuthwise(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"issuer": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderUsernamePassword returns tfsdk.Schema definition for ProviderUsernamePassword
func GenSchemaProviderUsernamePassword(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"forward_uri": schema.StringAttribute{
			Description: "ForwardURI URI to forward to",
			Optional:    true,
		},
		"password_hash_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"password_validators": schema.ListNestedAttribute{
			Description: "",
			NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"config": schema.SingleNestedAttribute{
					Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
					Description: "",
					Optional:    true,
				},
				"name": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"type": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
			}},
			Optional: true,
		},
	}}
}

// GenSchemaProviderMicrosoft returns tfsdk.Schema definition for ProviderMicrosoft
func GenSchemaProviderMicrosoft(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt_style": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderGoogle returns tfsdk.Schema definition for ProviderGoogle
func GenSchemaProviderGoogle(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderGitHub returns tfsdk.Schema definition for ProviderGitHub
func GenSchemaProviderGitHub(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"allow_signup": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"display": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderLinkedIn returns tfsdk.Schema definition for ProviderLinkedIn
func GenSchemaProviderLinkedIn(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"include_granted_scopes": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderFacebook returns tfsdk.Schema definition for ProviderFacebook
func GenSchemaProviderFacebook(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_fields": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderDropbox returns tfsdk.Schema definition for ProviderDropbox
func GenSchemaProviderDropbox(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"include_granted_scopes": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderOkta returns tfsdk.Schema definition for ProviderOkta
func GenSchemaProviderOkta(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderAuth0 returns tfsdk.Schema definition for ProviderAuth0
func GenSchemaProviderAuth0(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenant returns tfsdk.Schema definition for Tenant
func GenSchemaTenant(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"access_token_expire_seconds": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"cookie_domain": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"cors": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"allowed_headers": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"allowed_origins": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"options_mode": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"interaction_forward_uri": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"logging": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"include_caller": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"include_stack_trace": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"log_level": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
						"send_to_event_stream": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantUrl returns tfsdk.Schema definition for TenantUrl
func GenSchemaTenantUrl(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"cookie_domain": schema.StringAttribute{
				Description: "",
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProvider returns tfsdk.Schema definition for Provider
func GenSchemaProvider(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"type_url": schema.StringAttribute{
					Description: "A URL/resource name that uniquely identifies the type of the serialized protocol buffer message. This string must contain at least one \"/\" character. The last segment of the URL's path must represent the fully qualified name of the type (as in `path/google.protobuf.Duration`). The name should be in a canonical form (e.g., leading \".\" is not accepted). In practice, teams usually precompile into the binary all types that they expect it to use in the context of Any. However, for URLs which use the scheme `http`, `https`, or no scheme, one can optionally set up a type server that maps type URLs to message definitions as follows: * If no scheme is provided, `https` is assumed. * An HTTP GET on the URL must yield a [google.protobuf.Type][]   value in binary format, or produce an error. * Applications are allowed to cache lookup results based on the   URL, or have them precompiled into a binary to avoid any   lookup. Therefore, binary compatibility needs to be preserved   on changes to types. (Use versioned type names to manage   breaking changes.) Note: this functionality is not currently available in the official protobuf release, and it is not used for type URLs beginning with type.googleapis.com. Schemes other than `http`, `https` (or the empty scheme) might be used with implementation specific semantics.",
					Optional:    true,
				},
				"value": schema.StringAttribute{
					Description: "Must be a valid serialized protocol buffer of the above specified type.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"provider_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"realm_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaRealm returns tfsdk.Schema definition for Realm
func GenSchemaRealm(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"description": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:      true,
			Optional:      false,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			Required:      false,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_database_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAudience returns tfsdk.Schema definition for Audience
func GenSchemaAudience(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"access_token_expire_seconds": schema.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"cors": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"allowed_headers": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"allowed_origins": schema.ListAttribute{
							Description: "",
							ElementType: types.StringType,
							Optional:    true,
						},
						"options_mode": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"interaction_forward_uri": schema.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"logging": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"include_caller": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"include_stack_trace": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
						"log_level": schema.Int64Attribute{
							Description: "",
							Optional:    true,
						},
						"send_to_event_stream": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
				"scopes": schema.SingleNestedAttribute{
					Attributes: map[string]schema.Attribute{
						"authorization": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"include_permissions": schema.BoolAttribute{
									Description: "",
									Optional:    true,
								},
								"include_roles": schema.BoolAttribute{
									Description: "",
									Optional:    true,
								},
							},
							Description: "",
							Optional:    true,
						},
						"openid": schema.BoolAttribute{
							Description: "",
							Optional:    true,
						},
					},
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"description": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaClient returns tfsdk.Schema definition for Client
func GenSchemaClient(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"alias": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"type_url": schema.StringAttribute{
					Description: "A URL/resource name that uniquely identifies the type of the serialized protocol buffer message. This string must contain at least one \"/\" character. The last segment of the URL's path must represent the fully qualified name of the type (as in `path/google.protobuf.Duration`). The name should be in a canonical form (e.g., leading \".\" is not accepted). In practice, teams usually precompile into the binary all types that they expect it to use in the context of Any. However, for URLs which use the scheme `http`, `https`, or no scheme, one can optionally set up a type server that maps type URLs to message definitions as follows: * If no scheme is provided, `https` is assumed. * An HTTP GET on the URL must yield a [google.protobuf.Type][]   value in binary format, or produce an error. * Applications are allowed to cache lookup results based on the   URL, or have them precompiled into a binary to avoid any   lookup. Therefore, binary compatibility needs to be preserved   on changes to types. (Use versioned type names to manage   breaking changes.) Note: this functionality is not currently available in the official protobuf release, and it is not used for type URLs beginning with type.googleapis.com. Schemes other than `http`, `https` (or the empty scheme) might be used with implementation specific semantics.",
					Optional:    true,
				},
				"value": schema.StringAttribute{
					Description: "Must be a valid serialized protocol buffer of the above specified type.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"grant_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"login_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logo_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"metadata": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaRole returns tfsdk.Schema definition for Role
func GenSchemaRole(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaPermission returns tfsdk.Schema definition for Permission
func GenSchemaPermission(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaScope returns tfsdk.Schema definition for Scope
func GenSchemaScope(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"kind": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaEvent returns tfsdk.Schema definition for Event
func GenSchemaEvent(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"attributes": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"created_at": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"nanos": schema.Int64Attribute{
					Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
					Optional:    true,
				},
				"seconds": schema.Int64Attribute{
					Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"end_state": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"end_time": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"nanos": schema.Int64Attribute{
					Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
					Optional:    true,
				},
				"seconds": schema.Int64Attribute{
					Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"event_message": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"event_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"interaction_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"realm_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"request_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"session_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"start_state": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"start_time": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"nanos": schema.Int64Attribute{
					Description: "Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive.",
					Optional:    true,
				},
				"seconds": schema.Int64Attribute{
					Description: "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAppearanceProfile returns tfsdk.Schema definition for AppearanceProfile
func GenSchemaAppearanceProfile(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"theme_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTheme returns tfsdk.Schema definition for Theme
func GenSchemaTheme(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Attributes:  map[string]schema.Attribute{"fields": schema.MapAttribute{Description: "Unordered map of dynamically typed values."}},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaSecret returns tfsdk.Schema definition for Secret
func GenSchemaSecret(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"encoding": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"value": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAsset returns tfsdk.Schema definition for Asset
func GenSchemaAsset(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"mime_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
