// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	schema1 "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	objectdefault "github.com/hashicorp/terraform-plugin-framework/resource/schema/objectdefault"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// GenSchemaInteractiveClientConfigDataSource returns tfsdk.Schema definition for InteractiveClientConfig
func GenSchemaInteractiveClientConfigDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"allowed_redirect_uris": schema.ListAttribute{
			Description: "",
			ElementType: types.StringType,
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema1.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema1.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantConfigDataSource returns tfsdk.Schema definition for TenantConfig
func GenSchemaTenantConfigDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"cookie_domain": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema1.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema1.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantUrlConfigDataSource returns tfsdk.Schema definition for TenantUrlConfig
func GenSchemaTenantUrlConfigDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{"cookie_domain": schema.StringAttribute{
		Description: "",
		Optional:    true,
	}}}
}

// GenSchemaAudienceConfigDataSource returns tfsdk.Schema definition for AudienceConfig
func GenSchemaAudienceConfigDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"access_token_expire_seconds": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"cors": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"allowed_headers": schema1.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"allowed_origins": schema1.ListAttribute{
					Description: "",
					ElementType: types.StringType,
					Optional:    true,
				},
				"options_mode": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"interaction_forward_uri": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logging": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"include_caller": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"include_stack_trace": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
				"log_level": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"send_to_event_stream": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"scopes": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"authorization": schema1.SingleNestedAttribute{
					Computed:    true,
					Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
					Description: "",
					Optional:    true,
				},
				"openid": schema1.BoolAttribute{
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderAuthwiseDataSource returns tfsdk.Schema definition for ProviderAuthwise
func GenSchemaProviderAuthwiseDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"issuer": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderUsernamePasswordDataSource returns tfsdk.Schema definition for ProviderUsernamePassword
func GenSchemaProviderUsernamePasswordDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"forward_uri": schema.StringAttribute{
			Description: "ForwardURI URI to forward to",
			Optional:    true,
		},
		"password_hash_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"password_validators": schema.ListNestedAttribute{
			Description: "",
			NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"config": schema1.SingleNestedAttribute{
					Computed:    true,
					Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
					Description: "",
					Optional:    true,
				},
				"name": schema1.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"type": schema1.StringAttribute{
					Description: "",
					Optional:    true,
				},
			}},
			Optional: true,
		},
	}}
}

// GenSchemaProviderMicrosoftDataSource returns tfsdk.Schema definition for ProviderMicrosoft
func GenSchemaProviderMicrosoftDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt_style": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderGoogleDataSource returns tfsdk.Schema definition for ProviderGoogle
func GenSchemaProviderGoogleDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderGitHubDataSource returns tfsdk.Schema definition for ProviderGitHub
func GenSchemaProviderGitHubDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"allow_signup": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"display": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"prompt": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderLinkedInDataSource returns tfsdk.Schema definition for ProviderLinkedIn
func GenSchemaProviderLinkedInDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"include_granted_scopes": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderFacebookDataSource returns tfsdk.Schema definition for ProviderFacebook
func GenSchemaProviderFacebookDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_fields": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderDropboxDataSource returns tfsdk.Schema definition for ProviderDropbox
func GenSchemaProviderDropboxDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"include_granted_scopes": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderOktaDataSource returns tfsdk.Schema definition for ProviderOkta
func GenSchemaProviderOktaDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderAuth0DataSource returns tfsdk.Schema definition for ProviderAuth0
func GenSchemaProviderAuth0DataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantDataSource returns tfsdk.Schema definition for Tenant
func GenSchemaTenantDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"access_token_expire_seconds": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"cookie_domain": schema1.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"cors": schema1.SingleNestedAttribute{
					Computed:    true,
					Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
					Description: "",
					Optional:    true,
				},
				"interaction_forward_uri": schema1.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"logging": schema1.SingleNestedAttribute{
					Computed:    true,
					Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTenantUrlDataSource returns tfsdk.Schema definition for TenantUrl
func GenSchemaTenantUrlDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"cookie_domain": schema1.StringAttribute{
				Description: "",
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProviderDataSource returns tfsdk.Schema definition for Provider
func GenSchemaProviderDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"type_url": schema1.StringAttribute{
					Description: "A URL/resource name that uniquely identifies the type of the serialized protocol buffer message. This string must contain at least one \"/\" character. The last segment of the URL's path must represent the fully qualified name of the type (as in `path/google.protobuf.Duration`). The name should be in a canonical form (e.g., leading \".\" is not accepted). In practice, teams usually precompile into the binary all types that they expect it to use in the context of Any. However, for URLs which use the scheme `http`, `https`, or no scheme, one can optionally set up a type server that maps type URLs to message definitions as follows: * If no scheme is provided, `https` is assumed. * An HTTP GET on the URL must yield a [google.protobuf.Type][]   value in binary format, or produce an error. * Applications are allowed to cache lookup results based on the   URL, or have them precompiled into a binary to avoid any   lookup. Therefore, binary compatibility needs to be preserved   on changes to types. (Use versioned type names to manage   breaking changes.) Note: this functionality is not currently available in the official protobuf release, and it is not used for type URLs beginning with type.googleapis.com. Schemes other than `http`, `https` (or the empty scheme) might be used with implementation specific semantics.",
					Optional:    true,
				},
				"value": schema1.StringAttribute{
					Description: "Must be a valid serialized protocol buffer of the above specified type.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"provider_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"realm_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaRealmDataSource returns tfsdk.Schema definition for Realm
func GenSchemaRealmDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"description": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"user_database_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAudienceDataSource returns tfsdk.Schema definition for Audience
func GenSchemaAudienceDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"access_token_expire_seconds": schema1.Int64Attribute{
					Description: "",
					Optional:    true,
				},
				"cors": schema1.SingleNestedAttribute{
					Computed:    true,
					Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
					Description: "",
					Optional:    true,
				},
				"interaction_forward_uri": schema1.StringAttribute{
					Description: "",
					Optional:    true,
				},
				"logging": schema1.SingleNestedAttribute{
					Computed:    true,
					Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
					Description: "",
					Optional:    true,
				},
				"scopes": schema1.SingleNestedAttribute{
					Computed:    true,
					Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
					Description: "",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"description": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaClientDataSource returns tfsdk.Schema definition for Client
func GenSchemaClientDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"alias": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"appearance_profile_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"type_url": schema1.StringAttribute{
					Description: "A URL/resource name that uniquely identifies the type of the serialized protocol buffer message. This string must contain at least one \"/\" character. The last segment of the URL's path must represent the fully qualified name of the type (as in `path/google.protobuf.Duration`). The name should be in a canonical form (e.g., leading \".\" is not accepted). In practice, teams usually precompile into the binary all types that they expect it to use in the context of Any. However, for URLs which use the scheme `http`, `https`, or no scheme, one can optionally set up a type server that maps type URLs to message definitions as follows: * If no scheme is provided, `https` is assumed. * An HTTP GET on the URL must yield a [google.protobuf.Type][]   value in binary format, or produce an error. * Applications are allowed to cache lookup results based on the   URL, or have them precompiled into a binary to avoid any   lookup. Therefore, binary compatibility needs to be preserved   on changes to types. (Use versioned type names to manage   breaking changes.) Note: this functionality is not currently available in the official protobuf release, and it is not used for type URLs beginning with type.googleapis.com. Schemes other than `http`, `https` (or the empty scheme) might be used with implementation specific semantics.",
					Optional:    true,
				},
				"value": schema1.StringAttribute{
					Description: "Must be a valid serialized protocol buffer of the above specified type.",
					Optional:    true,
				},
			},
			Description: "",
			Optional:    true,
		},
		"grant_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"login_url": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"logo_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"metadata": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"fields": schema1.MapAttribute{
				Description: "Unordered map of dynamically typed values.",
				ElementType: types.StringType,
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaRoleDataSource returns tfsdk.Schema definition for Role
func GenSchemaRoleDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaPermissionDataSource returns tfsdk.Schema definition for Permission
func GenSchemaPermissionDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaScopeDataSource returns tfsdk.Schema definition for Scope
func GenSchemaScopeDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"kind": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAppearanceProfileDataSource returns tfsdk.Schema definition for AppearanceProfile
func GenSchemaAppearanceProfileDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"fields": schema1.MapAttribute{
				Description: "Unordered map of dynamically typed values.",
				ElementType: types.StringType,
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"fields": schema1.MapAttribute{
				Description: "Unordered map of dynamically typed values.",
				ElementType: types.StringType,
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"theme_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaThemeDataSource returns tfsdk.Schema definition for Theme
func GenSchemaThemeDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"fields": schema1.MapAttribute{
				Description: "Unordered map of dynamically typed values.",
				ElementType: types.StringType,
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{"fields": schema1.MapAttribute{
				Description: "Unordered map of dynamically typed values.",
				ElementType: types.StringType,
				Optional:    true,
			}},
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaSecretDataSource returns tfsdk.Schema definition for Secret
func GenSchemaSecretDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"encoding": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"value": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAssetDataSource returns tfsdk.Schema definition for Asset
func GenSchemaAssetDataSource(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"mime_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
