// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	objectdefault "github.com/hashicorp/terraform-plugin-framework/resource/schema/objectdefault"
	stringdefault "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// GenSchemaTenant returns tfsdk.Schema definition for Tenant
func GenSchemaTenant(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
	}}
}

// GenSchemaTenantUrl returns tfsdk.Schema definition for TenantUrl
func GenSchemaTenantUrl(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaProvider returns tfsdk.Schema definition for Provider
func GenSchemaProvider(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"config": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"provider_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"realm_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaRealm returns tfsdk.Schema definition for Realm
func GenSchemaRealm(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"description": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"user_database_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAudience returns tfsdk.Schema definition for Audience
func GenSchemaAudience(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"appearance_profile_id": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"description": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"tenant_id": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaClient returns tfsdk.Schema definition for Client
func GenSchemaClient(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"alias": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
		"appearance_profile_id": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
		"audience_id": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
		"config": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"grant_type": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"login_url": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
		"logo_id": schema.StringAttribute{
			Computed:    true,
			Default:     stringdefault.StaticString(""),
			Description: "",
			Optional:    true,
		},
		"metadata": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Required:    true,
		},
	}}
}

// GenSchemaRole returns tfsdk.Schema definition for Role
func GenSchemaRole(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaPermission returns tfsdk.Schema definition for Permission
func GenSchemaPermission(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaScope returns tfsdk.Schema definition for Scope
func GenSchemaScope(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"audience_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"auto": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"kind": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAppearanceProfile returns tfsdk.Schema definition for AppearanceProfile
func GenSchemaAppearanceProfile(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"theme_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaTheme returns tfsdk.Schema definition for Theme
func GenSchemaTheme(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"content": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"stylesheet_attributes": schema.SingleNestedAttribute{
			Computed:    true,
			Default:     objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})),
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaSecret returns tfsdk.Schema definition for Secret
func GenSchemaSecret(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"encoding": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"value": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// GenSchemaAsset returns tfsdk.Schema definition for Asset
func GenSchemaAsset(ctx context.Context) schema.Schema {
	return schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:    true,
			Description: "",
			Optional:    true,
		},
		"mime_type": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"tenant_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
