// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type scopeDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewScopeDataSource() datasource.DataSource {
	return &scopeDataSource{}
}

func (r *scopeDataSource) toModel(p *v1alpha11.Scope, m *scopeDataSourceModel) {
	m.Id = types.StringValue(p.Id)
	m.AudienceId = types.StringValue(p.AudienceId)
	m.Kind = types.StringValue(p.Kind)
	m.Auto = types.BoolValue(p.Auto)
}

type scopeDataSourceModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Kind       types.String `tfsdk:"kind"`
	Auto       types.Bool   `tfsdk:"auto"`
}

func (r *scopeDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *scopeDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_scope"
}

func (r *scopeDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data scopeDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetScopeRequest{Name: r.toName(data)}
	resp, err := r.client.GetScope(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Scope", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "scope read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
