// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type scopeResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewScope() resource.Resource {
	return &scopeResource{}
}

type scopeModel struct {
	Id         types.String `tfsdk:"id"`
	AudienceId types.String `tfsdk:"audience_id"`
	Kind       types.String `tfsdk:"kind"`
	Auto       types.Bool   `tfsdk:"auto"`
}

func (r *scopeResource) toName(data scopeModel) string {
	return fmt.Sprintf("audiences/%s/scopes/%s", data.AudienceId.ValueString(), data.Id.ValueString())
}
func (r *scopeResource) toParent(data scopeModel) string {
	return fmt.Sprintf("audiences/%s", data.AudienceId.ValueString())
}
func (r *scopeResource) toProto(m *scopeModel) (*v1alpha11.Scope, error) {

	return &v1alpha11.Scope{
		AudienceId: m.AudienceId.ValueString(),
		Auto:       m.Auto.ValueBool(),
		Id:         m.Id.ValueString(),
		Kind:       m.Kind.ValueString(),
	}, nil
}

func (r *scopeResource) toModel(p *v1alpha11.Scope, m *scopeModel) error {
	m.Id = types.StringValue(p.Id)
	m.AudienceId = types.StringValue(p.AudienceId)
	m.Kind = types.StringValue(p.Kind)
	m.Auto = types.BoolValue(p.Auto)
	return nil
}

func (r *scopeResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *scopeResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_scope"
}

func (r *scopeResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaScope(ctx)
}

func (r *scopeResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data scopeModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Scope to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreateScopeRequest{
		Parent: r.toParent(data),
		Scope:  val,
	}
	resp, err := r.client.CreateScope(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Scope", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Scope to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "scope create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *scopeResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data scopeModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetScopeRequest{Name: r.toName(data)}
	resp, err := r.client.GetScope(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Scope", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Scope to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "scope read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *scopeResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data scopeModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Scope to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdateScopeRequest{
		Name:  r.toName(data),
		Scope: val,
	}
	resp, err := r.client.UpdateScope(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Scope", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Scope to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "scope update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *scopeResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data scopeModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteScopeRequest{Name: r.toName(data)}
	_, err := r.client.DeleteScope(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Scope", err.Error())
		return
	}
	return
}
