// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type secretResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewSecret() resource.Resource {
	return &secretResource{}
}

type secretModel struct {
	Id       types.String `tfsdk:"id"`
	TenantId types.String `tfsdk:"tenant_id"`
	Name     types.String `tfsdk:"name"`
	Encoding types.Object `tfsdk:"encoding"`
	Value    types.String `tfsdk:"value"`
}

func (r *secretResource) toProto(m *secretModel) *v1alpha11.Secret {
	return &v1alpha11.Secret{
		Encoding: nil,
		Id:       m.Id.ValueString(),
		Name:     m.Name.ValueString(),
		TenantId: m.TenantId.ValueString(),
		Value:    m.Value.ValueString(),
	}
}

func (r *secretResource) toModel(p *v1alpha11.Secret, m *secretModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.Name = types.StringValue(p.Name)
	m.Value = types.StringValue(p.Value)
}

func (r *secretResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *secretResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_secret"
}

func (r *secretResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaSecret(ctx)
}

func (r *secretResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data secretModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.CreateSecretRequest{Secret: r.toProto(&data)}
	resp, err := r.client.CreateSecret(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Secret", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "secret create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *secretResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data secretModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetSecretRequest{Name: r.toName(data)}
	resp, err := r.client.GetSecret(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Secret", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "secret read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *secretResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data secretModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.UpdateSecretRequest{
		Name:   r.toName(data),
		Secret: r.toProto(&data),
	}
	resp, err := r.client.UpdateSecret(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Secret", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "secret update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *secretResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data secretModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteSecretRequest{Name: r.toName(data)}
	_, err := r.client.DeleteSecret(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Secret", err.Error())
		return
	}
	return
}
