// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	jsontypes "github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
	util "terraform-provider-authwise/internal/util"
)

type tenantUrlResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewTenantUrl() resource.Resource {
	return &tenantUrlResource{}
}

type tenantUrlModel struct {
	Id       types.String         `tfsdk:"id"`
	TenantId types.String         `tfsdk:"tenant_id"`
	Config   jsontypes.Normalized `tfsdk:"config"`
}

func (r *tenantUrlResource) toName(data tenantUrlModel) string {
	return fmt.Sprintf("tenant_urls/%s", data.Id.ValueString())
}
func (r *tenantUrlResource) toProto(m *tenantUrlModel) (*v1alpha11.TenantUrl, error) {
	converted_config, err := util.JsonToProtoConcrete[v1alpha11.TenantUrlConfig](m.Config)
	if err != nil {
		return nil, err
	}
	return &v1alpha11.TenantUrl{
		Config:   converted_config,
		Id:       m.Id.ValueString(),
		TenantId: m.TenantId.ValueString(),
	}, nil
}

func (r *tenantUrlResource) toModel(p *v1alpha11.TenantUrl, m *tenantUrlModel) error {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	return nil
}

func (r *tenantUrlResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *tenantUrlResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_tenant_url"
}

func (r *tenantUrlResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaTenantUrl(ctx)
}

func (r *tenantUrlResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data tenantUrlModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting TenantUrl to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreateTenantUrlRequest{TenantUrl: val}
	resp, err := r.client.CreateTenantUrl(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating TenantUrl", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting TenantUrl to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "tenanturl create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *tenantUrlResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data tenantUrlModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetTenantUrlRequest{Name: r.toName(data)}
	resp, err := r.client.GetTenantUrl(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading TenantUrl", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting TenantUrl to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "tenanturl read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *tenantUrlResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data tenantUrlModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting TenantUrl to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdateTenantUrlRequest{
		Name:      r.toName(data),
		TenantUrl: val,
	}
	resp, err := r.client.UpdateTenantUrl(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating TenantUrl", err.Error())
		return
	}

	err = r.toModel(resp, &data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting TenantUrl to Model", err.Error())
		return
	}
	tflog.Trace(ctx, "tenanturl update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *tenantUrlResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data tenantUrlModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteTenantUrlRequest{Name: r.toName(data)}
	_, err := r.client.DeleteTenantUrl(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting TenantUrl", err.Error())
		return
	}
	return
}
