// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
	util "terraform-provider-authwise/internal/util"
)

type tenantResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewTenant() resource.Resource {
	return &tenantResource{}
}

type tenantModel struct {
	Id                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	AppearanceProfileId types.String `tfsdk:"appearance_profile_id"`
	Config              types.Object `tfsdk:"config"`
}

func (r *tenantResource) toProto(m *tenantModel) (*v1alpha11.Tenant, error) {
	converted_config, err := util.ObjectToProtoConcrete[v1alpha11.TenantConfig](m.Config)
	if err != nil {
		return nil, err
	}
	return &v1alpha11.Tenant{
		AppearanceProfileId: m.AppearanceProfileId.ValueString(),
		Config:              converted_config,
		Id:                  m.Id.ValueString(),
		Name:                m.Name.ValueString(),
	}, nil
}

func (r *tenantResource) toModel(p *v1alpha11.Tenant, m *tenantModel) {
	m.Id = types.StringValue(p.Id)
	m.Name = types.StringValue(p.Name)
	m.AppearanceProfileId = types.StringValue(p.AppearanceProfileId)
}

func (r *tenantResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *tenantResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_tenant"
}

func (r *tenantResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaTenant(ctx)
}

func (r *tenantResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data tenantModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Tenant to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreateTenantRequest{Tenant: val}
	resp, err := r.client.CreateTenant(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Tenant", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "tenant create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *tenantResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data tenantModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetTenantRequest{Name: r.toName(data)}
	resp, err := r.client.GetTenant(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Tenant", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "tenant read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *tenantResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data tenantModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Tenant to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdateTenantRequest{
		Name:   r.toName(data),
		Tenant: val,
	}
	resp, err := r.client.UpdateTenant(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Tenant", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "tenant update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *tenantResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data tenantModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteTenantRequest{Name: r.toName(data)}
	_, err := r.client.DeleteTenant(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Tenant", err.Error())
		return
	}
	return
}
