// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
)

type themeDataSource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewThemeDataSource() datasource.DataSource {
	return &themeDataSource{}
}

func (r *themeDataSource) toName(data themeDataSourceModel) string {
	return fmt.Sprintf("themes/%s", data.Id.ValueString())
}
func (r *themeDataSource) toModel(p *v1alpha11.Theme, m *themeDataSourceModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.Name = types.StringValue(p.Name)
	m.Stylesheet = types.StringValue(p.Stylesheet)
}

type themeDataSourceModel struct {
	Id                   types.String `tfsdk:"id"`
	TenantId             types.String `tfsdk:"tenant_id"`
	Name                 types.String `tfsdk:"name"`
	Stylesheet           types.String `tfsdk:"stylesheet"`
	StylesheetAttributes types.Object `tfsdk:"stylesheet_attributes"`
	Content              types.Object `tfsdk:"content"`
}

func (r *themeDataSource) Configure(ctx context.Context, request datasource.ConfigureRequest, response *datasource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *themeDataSource) Metadata(ctx context.Context, request datasource.MetadataRequest, response *datasource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_theme"
}

func (r *themeDataSource) Schema(ctx context.Context, request datasource.SchemaRequest, response *datasource.SchemaResponse) {
	response.Schema = schema.Schema{Attributes: map[string]schema.Attribute{"id": schema.StringAttribute{
		Description: "",
		Required:    true,
	}}}
}

func (r *themeDataSource) Read(ctx context.Context, request datasource.ReadRequest, response *datasource.ReadResponse) {
	var data themeDataSourceModel

	response.Diagnostics.Append(request.Config.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetThemeRequest{Name: r.toName(data)}
	resp, err := r.client.GetTheme(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Theme", err.Error())
		return
	}

	r.toModel(resp, &data)

	tflog.Trace(ctx, "theme read")

	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}
