// Code generated by terraform-provider-authwise. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	v1alpha1 "gitlab.authwise.io/authwise/api-client-go/authwise/management/v1alpha1"
	v1alpha11 "gitlab.authwise.io/authwise/api-client-go/authwise/types/core/v1alpha1"
	util "terraform-provider-authwise/internal/util"
)

type themeResource struct {
	client v1alpha1.AuthwiseManagementServiceClient
}

func NewTheme() resource.Resource {
	return &themeResource{}
}

type themeModel struct {
	Id                   types.String `tfsdk:"id"`
	TenantId             types.String `tfsdk:"tenant_id"`
	Name                 types.String `tfsdk:"name"`
	Stylesheet           types.String `tfsdk:"stylesheet"`
	StylesheetAttributes types.Object `tfsdk:"stylesheet_attributes"`
	Content              types.Object `tfsdk:"content"`
}

func (r *themeResource) toProto(m *themeModel) (*v1alpha11.Theme, error) {
	converted_stylesheetattributes, err := util.ObjectToProtoStruct(m.StylesheetAttributes)
	if err != nil {
		return nil, err
	}
	converted_content, err := util.ObjectToProtoStruct(m.Content)
	if err != nil {
		return nil, err
	}
	return &v1alpha11.Theme{
		Content:              converted_content,
		Id:                   m.Id.ValueString(),
		Name:                 m.Name.ValueString(),
		Stylesheet:           m.Stylesheet.ValueString(),
		StylesheetAttributes: converted_stylesheetattributes,
		TenantId:             m.TenantId.ValueString(),
	}, nil
}

func (r *themeResource) toModel(p *v1alpha11.Theme, m *themeModel) {
	m.Id = types.StringValue(p.Id)
	m.TenantId = types.StringValue(p.TenantId)
	m.Name = types.StringValue(p.Name)
	m.Stylesheet = types.StringValue(p.Stylesheet)
}

func (r *themeResource) Configure(ctx context.Context, request resource.ConfigureRequest, response *resource.ConfigureResponse) {
	if request.ProviderData == nil {
		return
	}
	client, ok := request.ProviderData.(v1alpha1.AuthwiseManagementServiceClient)
	if !ok {
		response.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *v1alpha12.AuthwiseManagementServiceClient, got: %T. Please report this issue to the provider developers.", request.ProviderData))
		return
	}
	r.client = client
}

func (r *themeResource) Metadata(ctx context.Context, request resource.MetadataRequest, response *resource.MetadataResponse) {
	response.TypeName = request.ProviderTypeName + "_theme"
}

func (r *themeResource) Schema(ctx context.Context, request resource.SchemaRequest, response *resource.SchemaResponse) {
	response.Schema = GenSchemaTheme(ctx)
}

func (r *themeResource) Create(ctx context.Context, request resource.CreateRequest, response *resource.CreateResponse) {
	var data themeModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Theme to Proto", err.Error())
		return
	}

	req := &v1alpha1.CreateThemeRequest{Theme: val}
	resp, err := r.client.CreateTheme(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Creating Theme", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "theme create")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *themeResource) Read(ctx context.Context, request resource.ReadRequest, response *resource.ReadResponse) {
	var data themeModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.GetThemeRequest{Name: r.toName(data)}
	resp, err := r.client.GetTheme(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Reading Theme", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "theme read")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *themeResource) Update(ctx context.Context, request resource.UpdateRequest, response *resource.UpdateResponse) {
	var data themeModel

	response.Diagnostics.Append(request.Plan.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	val, err := r.toProto(&data)
	if err != nil {
		response.Diagnostics.AddError("Error Converting Theme to Proto", err.Error())
		return
	}

	req := &v1alpha1.UpdateThemeRequest{
		Name:  r.toName(data),
		Theme: val,
	}
	resp, err := r.client.UpdateTheme(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Updating Theme", err.Error())
		return
	}

	r.toModel(resp, &data)
	tflog.Trace(ctx, "theme update")
	response.Diagnostics.Append(response.State.Set(ctx, &data)...)
}

func (r *themeResource) Delete(ctx context.Context, request resource.DeleteRequest, response *resource.DeleteResponse) {
	var data themeModel

	response.Diagnostics.Append(request.State.Get(ctx, &data)...)

	if response.Diagnostics.HasError() {
		return
	}

	req := &v1alpha1.DeleteThemeRequest{Name: r.toName(data)}
	_, err := r.client.DeleteTheme(ctx, req)
	if err != nil {
		response.Diagnostics.AddError("Error Deleting Theme", err.Error())
		return
	}
	return
}
